Fronkensteen.procedureDefinitionPointers = {
"eqv?":{
"filename":"root/biwascheme.js",
"line":3953,
"documentation":"(eqv%3F%20obj1%20obj2)%E2%80%8C%E2%80%8C%0A%0AThe%20eqv%3F%20procedure%20defines%20a%20useful%20equivalence%20relation%20on%20objects.%20Briefly%2C%20it%20returns%20%23t%20if%20obj1%20and%20obj2%20should%20normally%20be%20regarded%20as%20the%20same%20object%20and%20%23f%20otherwise.%20This%20relation%20is%20left%20slightly%20open%20to%20interpretation%2C%20but%20the%20following%20partial%20specification%20of%20eqv%3F%20must%20hold%20for%20all%20implementations.%0A%0AThe%20eqv%3F%20procedure%20returns%20%23t%20if%20one%20of%20the%20following%20holds%3A%0A%0A%20%20%20%20Obj1%20and%20obj2%20are%20both%20booleans%20and%20are%20the%20same%20according%20to%20the%20boolean%3D%3F%20procedure.%0A%0A%20%20%20%20Obj1%20and%20obj2%20are%20both%20symbols%20and%20are%20the%20same%20according%20to%20the%20symbol%3D%3F%20procedure.%0A%0A%20%20%20%20Obj1%20and%20obj2%20are%20both%20exactnumber%20objects%20and%20are%20numerically%20equal%20(see%20%3D).%0A%0A%20%20%20%20Obj1%20and%20obj2%20are%20both%20inexactnumber%20objects%2C%20are%20numerically%20equal%20(see%20%3D)%2C%20and%20yield%20the%20same%20results%20(in%20the%20sense%20of%20eqv%3F)%20when%20passed%20as%20arguments%20to%20any%20other%20procedure%20that%20can%20be%20defined%20as%20a%20finite%20composition%20of%20Scheme's%20standard%20arithmetic%20procedures.%0A%0A%20%20%20%20Obj1%20and%20obj2%20are%20both%20characters%20and%20are%20the%20same%20character%20according%20to%20the%20char%3D%3F%20procedure%20.%0A%0A%20%20%20%20Both%20obj1%20and%20obj2%20are%20the%20empty%20list.%0A%0A%20%20%20%20Obj1%20and%20obj2%20are%20objects%20such%20as%20pairs%2C%20vectors%2C%20bytevectors%20(library%20chapter%20on%20%E2%80%9CBytevectors%E2%80%9D)%2C%20strings%2C%20hashtables%2C%20records%20(library%20chapter%20on%20%E2%80%9CRecords%E2%80%9D)%2C%20ports%20(library%20section%20on%20%E2%80%9CPort%20I%2FO%E2%80%9D)%2C%20or%20hashtables%20(library%20chapter%20on%20%E2%80%9CHash%20tables%E2%80%9D)%20that%20refer%20to%20the%20same%20locations%20in%20the%20store%20(section%205.10).%0A%0A%20%20%20%20Obj1%20and%20obj2%20are%20record-type%20descriptors%20that%20are%20specified%20to%20be%20eqv%3F%20in%20library%20section%20on%20%E2%80%9CProcedural%20layer%E2%80%9D.%0A%0AThe%20eqv%3F%20procedure%20returns%20%23f%20if%20one%20of%20the%20following%20holds%3A%0A%0A%20%20%20%20Obj1%20and%20obj2%20are%20of%20different%20types.%0A%0A%20%20%20%20Obj1%20and%20obj2%20are%20booleans%20for%20which%20the%20boolean%3D%3F%20procedure%20returns%20%23f.%0A%0A%20%20%20%20Obj1%20and%20obj2%20are%20symbols%20for%20which%20the%20symbol%3D%3F%20procedure%20returns%20%23f.%0A%0A%20%20%20%20One%20of%20obj1%20and%20obj2%20is%20an%20exact%20number%20object%20but%20the%20other%20is%20an%20inexact%20number%20object.%0A%0A%20%20%20%20Obj1%20and%20obj2%20are%20rational%20number%20objects%20for%20which%20the%20%3D%20procedure%20returns%20%23f.%0A%0A%20%20%20%20Obj1%20and%20obj2%20yield%20different%20results%20(in%20the%20sense%20of%20eqv%3F)%20when%20passed%20as%20arguments%20to%20any%20other%20procedure%20that%20can%20be%20defined%20as%20a%20finite%20composition%20of%20Scheme's%20standard%20arithmetic%20procedures.%0A%0A%20%20%20%20Obj1%20and%20obj2%20are%20characters%20for%20which%20the%20char%3D%3F%20procedure%20returns%20%23f.%0A%0A%20%20%20%20One%20of%20obj1%20and%20obj2%20is%20the%20empty%20list%2C%20but%20the%20other%20is%20not.%0A%0A%20%20%20%20Obj1%20and%20obj2%20are%20objects%20such%20as%20pairs%2C%20vectors%2C%20bytevectors%20(library%20chapter%20on%20%E2%80%9CBytevectors%E2%80%9D)%2C%20strings%2C%20records%20(library%20chapter%20on%20%E2%80%9CRecords%E2%80%9D)%2C%20ports%20(library%20section%20on%20%E2%80%9CPort%20I%2FO%E2%80%9D)%2C%20or%20hashtables%20(library%20chapter%20on%20%E2%80%9CHashtables%E2%80%9D)%20that%20refer%20to%20distinct%20locations.%0A%0A%20%20%20%20Obj1%20and%20obj2%20are%20pairs%2C%20vectors%2C%20strings%2C%20or%20records%2C%20or%20hashtables%2C%20where%20the%20applying%20the%20same%20accessor%20(i.e.%20car%2C%20cdr%2C%20vector-ref%2C%20string-ref%2C%20or%20record%20accessors)%20to%20both%20yields%20results%20for%20which%20eqv%3F%20returns%20%23f.%0A%0A%20%20%20%20Obj1%20and%20obj2%20are%20procedures%20that%20would%20behave%20differently%20(return%20different%20values%20or%20have%20different%20side%20effects)%20for%20some%20arguments.%0A%0A%20%20%20%20Note%3A%E2%80%8C%20The%20eqv%3F%20procedure%20returning%20%23t%20when%20obj1%20and%20obj2%20are%20number%20objects%20does%20not%20imply%20that%20%3D%20would%20also%20return%20%23t%20when%20called%20with%20obj1%20and%20obj2%20as%20arguments.%20%0A%0A(eqv%3F%20'a%20'a)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20%23t%0A%0A(eqv%3F%20'a%20'b)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20%23f%0A%0A(eqv%3F%202%202)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20%23t%0A%0A(eqv%3F%20'()%20'())%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20%23t%0A%0A(eqv%3F%20100000000%20100000000)%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20%23t%0A%0A(eqv%3F%20(cons%201%202)%20(cons%201%202))%20%20%20%20%20%E2%80%8C%E2%87%92%20%20%23f%0A%0A(eqv%3F%20(lambda%20()%201)%0A%0A%20%20%20%20%20%20(lambda%20()%202))%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20%23f%0A%0A(eqv%3F%20%23f%20'nil)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20%23f%0A%0AThe%20following%20examples%20illustrate%20cases%20in%20which%20the%20above%20rules%20do%20not%20fully%20specify%20the%20behavior%20of%20eqv%3F.%20All%20that%20can%20be%20said%20about%20such%20cases%20is%20that%20the%20value%20returned%20by%20eqv%3F%20must%20be%20a%20boolean.%0A%0A(let%20((p%20(lambda%20(x)%20x)))%0A%0A%20%20(eqv%3F%20p%20p))%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20unspecified%0A%0A(eqv%3F%20%22%22%20%22%22)%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20unspecified%0A%0A(eqv%3F%20'%23()%20'%23())%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20unspecified%0A%0A(eqv%3F%20(lambda%20(x)%20x)%0A%0A%20%20%20%20%20%20(lambda%20(x)%20x))%20%20%20%20%E2%80%8C%E2%87%92%20%20unspecified%0A%0A(eqv%3F%20(lambda%20(x)%20x)%0A%0A%20%20%20%20%20%20(lambda%20(y)%20y))%20%20%20%20%E2%80%8C%E2%87%92%20%20unspecified%0A%0A(eqv%3F%20%2Bnan.0%20%2Bnan.0)%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20unspecified%0A%0AThe%20next%20set%20of%20examples%20shows%20the%20use%20of%20eqv%3F%20with%20procedures%20that%20have%20local%20state.%20Calls%20to%20gen-counter%20must%20return%20a%20distinct%20procedure%20every%20time%2C%20since%20each%20procedure%20has%20its%20own%20internal%20counter.%20Calls%20to%20gen-loser%20return%20procedures%20that%20behave%20equivalently%20when%20called.%20However%2C%20eqv%3F%20may%20not%20detect%20this%20equivalence.%0A%0A(define%20gen-counter%0A%20%20(lambda%20()%0A%20%20%20%20(let%20((n%200))%0A%20%20%20%20%20%20(lambda%20()%20(set!%20n%20(%2B%20n%201))%20n))))%0A%0A(let%20((g%20(gen-counter)))%0A%20%20(eqv%3F%20g%20g))%20%20%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20unspecified%0A%0A(eqv%3F%20(gen-counter)%20(gen-counter))%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20%23f%0A%0A(define%20gen-loser%0A%20%20(lambda%20()%0A%20%20%20%20(let%20((n%200))%0A%20%20%20%20%20%20(lambda%20()%20(set!%20n%20(%2B%20n%201))%2027))))%0A%0A(let%20((g%20(gen-loser)))%0A%20%20(eqv%3F%20g%20g))%20%20%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20unspecified%0A%0A(eqv%3F%20(gen-loser)%20(gen-loser))%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20unspecified%0A%0A(letrec%20((f%20(lambda%20()%20(if%20(eqv%3F%20f%20g)%20'both%20'f)))%0A%20%20%20%20%20%20%20%20%20(g%20(lambda%20()%20(if%20(eqv%3F%20f%20g)%20'both%20'g))))%0A%0A%20%20(eqv%3F%20f%20g))%20%E2%80%8C%E2%87%92%20%20unspecified%0A%0A(letrec%20((f%20(lambda%20()%20(if%20(eqv%3F%20f%20g)%20'f%20'both)))%0A%20%20%20%20%20%20%20%20%20(g%20(lambda%20()%20(if%20(eqv%3F%20f%20g)%20'g%20'both))))%0A%0A%20%20(eqv%3F%20f%20g))%20%E2%80%8C%E2%87%92%20%20%23f%0A%0AImplementations%20may%20share%20structure%20between%20constants%20where%20appropriate.%20Furthermore%2C%20a%20constant%20may%20be%20copied%20at%20any%20time%20by%20the%20implementation%20so%20as%20to%20exist%20simultaneously%20in%20different%20sets%20of%20locations%2C%20as%20noted%20in%20section%2011.4.1.%20Thus%20the%20value%20of%20eqv%3F%20on%20constants%20is%20sometimes%20implementation-dependent.%0A%0A(eqv%3F%20'(a)%20'(a))%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20unspecified%0A%0A(eqv%3F%20%22a%22%20%22a%22)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20unspecified%0A%0A(eqv%3F%20'(b)%20(cdr%20'(a%20b)))%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20unspecified%0A%0A(let%20((x%20'(a)))%0A%20%20(eqv%3F%20x%20x))%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%80%8C%E2%87%92%20%20%23t%0A"}
,
"eq?":{
"filename":"root/biwascheme.js",
"line":3956,
"documentation":""}
,
"equal?":{
"filename":"root/biwascheme.js",
"line":3959,
"documentation":""}
,
"procedure?":{
"filename":"root/biwascheme.js",
"line":3967,
"documentation":""}
,
"number?":{
"filename":"root/biwascheme.js",
"line":3988,
"documentation":""}
,
"complex?":{
"filename":"root/biwascheme.js",
"line":3991,
"documentation":""}
,
"real?":{
"filename":"root/biwascheme.js",
"line":3994,
"documentation":""}
,
"rational?":{
"filename":"root/biwascheme.js",
"line":3997,
"documentation":""}
,
"integer?":{
"filename":"root/biwascheme.js",
"line":4000,
"documentation":""}
,
"=":{
"filename":"root/biwascheme.js",
"line":4019,
"documentation":""}
,
"<":{
"filename":"root/biwascheme.js",
"line":4029,
"documentation":""}
,
">":{
"filename":"root/biwascheme.js",
"line":4037,
"documentation":""}
,
"<=":{
"filename":"root/biwascheme.js",
"line":4045,
"documentation":""}
,
">=":{
"filename":"root/biwascheme.js",
"line":4053,
"documentation":""}
,
"zero?":{
"filename":"root/biwascheme.js",
"line":4062,
"documentation":""}
,
"positive?":{
"filename":"root/biwascheme.js",
"line":4066,
"documentation":""}
,
"negative?":{
"filename":"root/biwascheme.js",
"line":4070,
"documentation":""}
,
"odd?":{
"filename":"root/biwascheme.js",
"line":4074,
"documentation":""}
,
"even?":{
"filename":"root/biwascheme.js",
"line":4078,
"documentation":""}
,
"finite?":{
"filename":"root/biwascheme.js",
"line":4082,
"documentation":""}
,
"infinite?":{
"filename":"root/biwascheme.js",
"line":4086,
"documentation":""}
,
"nan?":{
"filename":"root/biwascheme.js",
"line":4090,
"documentation":""}
,
"max":{
"filename":"root/biwascheme.js",
"line":4094,
"documentation":""}
,
"min":{
"filename":"root/biwascheme.js",
"line":4100,
"documentation":""}
,
"+":{
"filename":"root/biwascheme.js",
"line":4115,
"documentation":""}
,
"*":{
"filename":"root/biwascheme.js",
"line":4133,
"documentation":""}
,
"-":{
"filename":"root/biwascheme.js",
"line":4143,
"documentation":""}
,
"/":{
"filename":"root/biwascheme.js",
"line":4163,
"documentation":""}
,
"abs":{
"filename":"root/biwascheme.js",
"line":4183,
"documentation":""}
,
"div0-and-mod0":{
"filename":"root/biwascheme.js",
"line":4216,
"documentation":""}
,
"div":{
"filename":"root/biwascheme.js",
"line":4206,
"documentation":""}
,
"mod":{
"filename":"root/biwascheme.js",
"line":4211,
"documentation":""}
,
"div0":{
"filename":"root/biwascheme.js",
"line":4221,
"documentation":""}
,
"mod0":{
"filename":"root/biwascheme.js",
"line":4226,
"documentation":""}
,
"numerator":{
"filename":"root/biwascheme.js",
"line":4235,
"documentation":""}
,
"denominator":{
"filename":"root/biwascheme.js",
"line":4242,
"documentation":""}
,
"floor":{
"filename":"root/biwascheme.js",
"line":4249,
"documentation":""}
,
"ceiling":{
"filename":"root/biwascheme.js",
"line":4253,
"documentation":""}
,
"truncate":{
"filename":"root/biwascheme.js",
"line":4257,
"documentation":""}
,
"round":{
"filename":"root/biwascheme.js",
"line":4261,
"documentation":""}
,
"exp":{
"filename":"root/biwascheme.js",
"line":4268,
"documentation":""}
,
"log":{
"filename":"root/biwascheme.js",
"line":4272,
"documentation":""}
,
"sin":{
"filename":"root/biwascheme.js",
"line":4283,
"documentation":""}
,
"cos":{
"filename":"root/biwascheme.js",
"line":4287,
"documentation":""}
,
"tan":{
"filename":"root/biwascheme.js",
"line":4291,
"documentation":""}
,
"asin":{
"filename":"root/biwascheme.js",
"line":4295,
"documentation":""}
,
"acos":{
"filename":"root/biwascheme.js",
"line":4299,
"documentation":""}
,
"atan":{
"filename":"root/biwascheme.js",
"line":4303,
"documentation":""}
,
"sqrt":{
"filename":"root/biwascheme.js",
"line":4312,
"documentation":""}
,
"exact-integer-sqrt":{
"filename":"root/biwascheme.js",
"line":4316,
"documentation":""}
,
"expt":{
"filename":"root/biwascheme.js",
"line":4324,
"documentation":""}
,
"make-rectangular":{
"filename":"root/biwascheme.js",
"line":4329,
"documentation":""}
,
"make-polar":{
"filename":"root/biwascheme.js",
"line":4334,
"documentation":""}
,
"real-part":{
"filename":"root/biwascheme.js",
"line":4345,
"documentation":""}
,
"imag-part":{
"filename":"root/biwascheme.js",
"line":4349,
"documentation":""}
,
"magnitude":{
"filename":"root/biwascheme.js",
"line":4353,
"documentation":""}
,
"angle":{
"filename":"root/biwascheme.js",
"line":4357,
"documentation":""}
,
"number->string":{
"filename":"root/biwascheme.js",
"line":4365,
"documentation":""}
,
"string->number":{
"filename":"root/biwascheme.js",
"line":4373,
"documentation":""}
,
"not":{
"filename":"root/biwascheme.js",
"line":4414,
"documentation":""}
,
"boolean?":{
"filename":"root/biwascheme.js",
"line":4417,
"documentation":""}
,
"boolean=?":{
"filename":"root/biwascheme.js",
"line":4420,
"documentation":""}
,
"pair?":{
"filename":"root/biwascheme.js",
"line":4430,
"documentation":""}
,
"cons":{
"filename":"root/biwascheme.js",
"line":4433,
"documentation":""}
,
"car":{
"filename":"root/biwascheme.js",
"line":4436,
"documentation":"Evaluates to the first item in the pair (the first item on the list,
 if pair is a list)."}
,
"cdr":{
"filename":"root/biwascheme.js",
"line":4441,
"documentation":""}
,
"set-car!":{
"filename":"root/biwascheme.js",
"line":4446,
"documentation":""}
,
"set-cdr!":{
"filename":"root/biwascheme.js",
"line":4451,
"documentation":""}
,
"caar":{
"filename":"root/biwascheme.js",
"line":4472,
"documentation":""}
,
"cadr":{
"filename":"root/biwascheme.js",
"line":4473,
"documentation":""}
,
"cdar":{
"filename":"root/biwascheme.js",
"line":4474,
"documentation":""}
,
"cddr":{
"filename":"root/biwascheme.js",
"line":4475,
"documentation":""}
,
"caaar":{
"filename":"root/biwascheme.js",
"line":4477,
"documentation":""}
,
"caadr":{
"filename":"root/biwascheme.js",
"line":4478,
"documentation":""}
,
"cadar":{
"filename":"root/biwascheme.js",
"line":4479,
"documentation":""}
,
"caddr":{
"filename":"root/biwascheme.js",
"line":4480,
"documentation":""}
,
"cdaar":{
"filename":"root/biwascheme.js",
"line":4481,
"documentation":""}
,
"cdadr":{
"filename":"root/biwascheme.js",
"line":4482,
"documentation":""}
,
"cddar":{
"filename":"root/biwascheme.js",
"line":4483,
"documentation":""}
,
"cdddr":{
"filename":"root/biwascheme.js",
"line":4484,
"documentation":""}
,
"caaaar":{
"filename":"root/biwascheme.js",
"line":4486,
"documentation":""}
,
"caaadr":{
"filename":"root/biwascheme.js",
"line":4487,
"documentation":""}
,
"caadar":{
"filename":"root/biwascheme.js",
"line":4488,
"documentation":""}
,
"caaddr":{
"filename":"root/biwascheme.js",
"line":4489,
"documentation":""}
,
"cadaar":{
"filename":"root/biwascheme.js",
"line":4490,
"documentation":""}
,
"cadadr":{
"filename":"root/biwascheme.js",
"line":4491,
"documentation":""}
,
"caddar":{
"filename":"root/biwascheme.js",
"line":4492,
"documentation":""}
,
"cadddr":{
"filename":"root/biwascheme.js",
"line":4493,
"documentation":""}
,
"cdaaar":{
"filename":"root/biwascheme.js",
"line":4494,
"documentation":""}
,
"cdaadr":{
"filename":"root/biwascheme.js",
"line":4495,
"documentation":""}
,
"cdadar":{
"filename":"root/biwascheme.js",
"line":4496,
"documentation":""}
,
"cdaddr":{
"filename":"root/biwascheme.js",
"line":4497,
"documentation":""}
,
"cddaar":{
"filename":"root/biwascheme.js",
"line":4498,
"documentation":""}
,
"cddadr":{
"filename":"root/biwascheme.js",
"line":4499,
"documentation":""}
,
"cdddar":{
"filename":"root/biwascheme.js",
"line":4500,
"documentation":""}
,
"cddddr":{
"filename":"root/biwascheme.js",
"line":4501,
"documentation":""}
,
"null?":{
"filename":"root/biwascheme.js",
"line":4504,
"documentation":""}
,
"list?":{
"filename":"root/biwascheme.js",
"line":4507,
"documentation":""}
,
"list":{
"filename":"root/biwascheme.js",
"line":4510,
"documentation":""}
,
"length":{
"filename":"root/biwascheme.js",
"line":4516,
"documentation":""}
,
"append":{
"filename":"root/biwascheme.js",
"line":4523,
"documentation":""}
,
"reverse":{
"filename":"root/biwascheme.js",
"line":4533,
"documentation":""}
,
"list-tail":{
"filename":"root/biwascheme.js",
"line":4544,
"documentation":""}
,
"list-ref":{
"filename":"root/biwascheme.js",
"line":4557,
"documentation":""}
,
"map":{
"filename":"root/biwascheme.js",
"line":4570,
"documentation":""}
,
"for-each":{
"filename":"root/biwascheme.js",
"line":4596,
"documentation":""}
,
"symbol?":{
"filename":"root/biwascheme.js",
"line":4610,
"documentation":""}
,
"symbol->string":{
"filename":"root/biwascheme.js",
"line":4613,
"documentation":""}
,
"symbol=?":{
"filename":"root/biwascheme.js",
"line":4617,
"documentation":""}
,
"string->symbol":{
"filename":"root/biwascheme.js",
"line":4625,
"documentation":""}
,
"char?":{
"filename":"root/biwascheme.js",
"line":4633,
"documentation":""}
,
"char->integer":{
"filename":"root/biwascheme.js",
"line":4636,
"documentation":""}
,
"integer->char":{
"filename":"root/biwascheme.js",
"line":4640,
"documentation":""}
,
"char=?":{
"filename":"root/biwascheme.js",
"line":4656,
"documentation":""}
,
"char<?":{
"filename":"root/biwascheme.js",
"line":4658,
"documentation":""}
,
"char>?":{
"filename":"root/biwascheme.js",
"line":4660,
"documentation":""}
,
"char<=?":{
"filename":"root/biwascheme.js",
"line":4662,
"documentation":""}
,
"char>=?":{
"filename":"root/biwascheme.js",
"line":4664,
"documentation":""}
,
"string?":{
"filename":"root/biwascheme.js",
"line":4670,
"documentation":""}
,
"make-string":{
"filename":"root/biwascheme.js",
"line":4673,
"documentation":""}
,
"string":{
"filename":"root/biwascheme.js",
"line":4684,
"documentation":""}
,
"string-length":{
"filename":"root/biwascheme.js",
"line":4690,
"documentation":""}
,
"string-ref":{
"filename":"root/biwascheme.js",
"line":4694,
"documentation":""}
,
"string=?":{
"filename":"root/biwascheme.js",
"line":4699,
"documentation":""}
,
"string<?":{
"filename":"root/biwascheme.js",
"line":4707,
"documentation":""}
,
"string>?":{
"filename":"root/biwascheme.js",
"line":4715,
"documentation":""}
,
"string<=?":{
"filename":"root/biwascheme.js",
"line":4723,
"documentation":""}
,
"string>=?":{
"filename":"root/biwascheme.js",
"line":4731,
"documentation":""}
,
"substring":{
"filename":"root/biwascheme.js",
"line":4740,
"documentation":""}
,
"string-append":{
"filename":"root/biwascheme.js",
"line":4754,
"documentation":"(string-append%20string%20...)%E2%80%8C%E2%80%8C%0A%0AReturns%20a%20newly%20allocated%20string%20whose%20characters%20form%20the%20concatenation%20of%20the%20given%20strings.%20"}
,
"string->list":{
"filename":"root/biwascheme.js",
"line":4760,
"documentation":""}
,
"list->string":{
"filename":"root/biwascheme.js",
"line":4764,
"documentation":""}
,
"string-for-each":{
"filename":"root/biwascheme.js",
"line":4768,
"documentation":""}
,
"string-copy":{
"filename":"root/biwascheme.js",
"line":4777,
"documentation":""}
,
"vector?":{
"filename":"root/biwascheme.js",
"line":4787,
"documentation":""}
,
"make-vector":{
"filename":"root/biwascheme.js",
"line":4790,
"documentation":"(make-vector%20k)%E2%80%8C%E2%80%8C%20%0A(make-vector%20k%20fill)%20%E2%80%8C%E2%80%8C%0A%0AReturns%20a%20newly%20allocated%20vector%20of%20k%20elements.%20If%20a%20second%20argument%20is%20given%2C%20then%20each%20element%20is%20initialized%20to%20fill.%20Otherwise%20the%20initial%20contents%20of%20each%20element%20is%20unspecified."}
,
"vector":{
"filename":"root/biwascheme.js",
"line":4800,
"documentation":""}
,
"vector-length":{
"filename":"root/biwascheme.js",
"line":4803,
"documentation":""}
,
"vector-ref":{
"filename":"root/biwascheme.js",
"line":4807,
"documentation":""}
,
"vector-set!":{
"filename":"root/biwascheme.js",
"line":4814,
"documentation":""}
,
"vector->list":{
"filename":"root/biwascheme.js",
"line":4821,
"documentation":""}
,
"list->vector":{
"filename":"root/biwascheme.js",
"line":4825,
"documentation":""}
,
"vector-fill!":{
"filename":"root/biwascheme.js",
"line":4829,
"documentation":""}
,
"vector-map":{
"filename":"root/biwascheme.js",
"line":4837,
"documentation":""}
,
"vector-for-each":{
"filename":"root/biwascheme.js",
"line":4848,
"documentation":""}
,
"apply":{
"filename":"root/biwascheme.js",
"line":4868,
"documentation":""}
,
"values":{
"filename":"root/biwascheme.js",
"line":4878,
"documentation":""}
,
"call-with-values":{
"filename":"root/biwascheme.js",
"line":4884,
"documentation":""}
,
"string-upcase":{
"filename":"root/biwascheme.js",
"line":5044,
"documentation":""}
,
"string-downcase":{
"filename":"root/biwascheme.js",
"line":5049,
"documentation":""}
,
"string-ci=?":{
"filename":"root/biwascheme.js",
"line":5070,
"documentation":""}
,
"string-ci<?":{
"filename":"root/biwascheme.js",
"line":5073,
"documentation":""}
,
"string-ci>?":{
"filename":"root/biwascheme.js",
"line":5076,
"documentation":""}
,
"string-ci<=?":{
"filename":"root/biwascheme.js",
"line":5079,
"documentation":""}
,
"string-ci>=?":{
"filename":"root/biwascheme.js",
"line":5082,
"documentation":""}
,
"find":{
"filename":"root/biwascheme.js",
"line":5097,
"documentation":""}
,
"for-all":{
"filename":"root/biwascheme.js",
"line":5106,
"documentation":""}
,
"exists":{
"filename":"root/biwascheme.js",
"line":5123,
"documentation":""}
,
"filter":{
"filename":"root/biwascheme.js",
"line":5138,
"documentation":""}
,
"partition":{
"filename":"root/biwascheme.js",
"line":5159,
"documentation":""}
,
"fold-left":{
"filename":"root/biwascheme.js",
"line":5175,
"documentation":""}
,
"fold-right":{
"filename":"root/biwascheme.js",
"line":5189,
"documentation":""}
,
"remp":{
"filename":"root/biwascheme.js",
"line":5207,
"documentation":""}
,
"remove":{
"filename":"root/biwascheme.js",
"line":5233,
"documentation":""}
,
"remv":{
"filename":"root/biwascheme.js",
"line":5234,
"documentation":""}
,
"remq":{
"filename":"root/biwascheme.js",
"line":5235,
"documentation":""}
,
"memp":{
"filename":"root/biwascheme.js",
"line":5237,
"documentation":""}
,
"member":{
"filename":"root/biwascheme.js",
"line":5263,
"documentation":""}
,
"memv":{
"filename":"root/biwascheme.js",
"line":5264,
"documentation":""}
,
"memq":{
"filename":"root/biwascheme.js",
"line":5265,
"documentation":""}
,
"assp":{
"filename":"root/biwascheme.js",
"line":5267,
"documentation":""}
,
"assoc":{
"filename":"root/biwascheme.js",
"line":5302,
"documentation":""}
,
"assv":{
"filename":"root/biwascheme.js",
"line":5303,
"documentation":""}
,
"assq":{
"filename":"root/biwascheme.js",
"line":5304,
"documentation":""}
,
"cons*":{
"filename":"root/biwascheme.js",
"line":5306,
"documentation":""}
,
"list-sort":{
"filename":"root/biwascheme.js",
"line":5401,
"documentation":""}
,
"vector-sort":{
"filename":"root/biwascheme.js",
"line":5416,
"documentation":""}
,
"vector-sort!":{
"filename":"root/biwascheme.js",
"line":5431,
"documentation":""}
,
"_define-record-type":{
"filename":"root/biwascheme.js",
"line":5779,
"documentation":""}
,
"_record-type-descriptor":{
"filename":"root/biwascheme.js",
"line":5791,
"documentation":""}
,
"_record-constructor-descriptor":{
"filename":"root/biwascheme.js",
"line":5804,
"documentation":""}
,
"make-record-type-descriptor":{
"filename":"root/biwascheme.js",
"line":5815,
"documentation":""}
,
"record-type-descriptor?":{
"filename":"root/biwascheme.js",
"line":5849,
"documentation":""}
,
"make-record-constructor-descriptor":{
"filename":"root/biwascheme.js",
"line":5854,
"documentation":""}
,
"record-constructor":{
"filename":"root/biwascheme.js",
"line":5865,
"documentation":""}
,
"record-predicate":{
"filename":"root/biwascheme.js",
"line":5873,
"documentation":""}
,
"record-accessor":{
"filename":"root/biwascheme.js",
"line":5886,
"documentation":""}
,
"record-mutator":{
"filename":"root/biwascheme.js",
"line":5911,
"documentation":""}
,
"record?":{
"filename":"root/biwascheme.js",
"line":5935,
"documentation":""}
,
"record-rtd":{
"filename":"root/biwascheme.js",
"line":5948,
"documentation":""}
,
"record-type-name":{
"filename":"root/biwascheme.js",
"line":5954,
"documentation":""}
,
"record-type-parent":{
"filename":"root/biwascheme.js",
"line":5960,
"documentation":""}
,
"record-type-uid":{
"filename":"root/biwascheme.js",
"line":5966,
"documentation":""}
,
"record-type-generative?":{
"filename":"root/biwascheme.js",
"line":5972,
"documentation":""}
,
"record-type-sealed?":{
"filename":"root/biwascheme.js",
"line":5978,
"documentation":""}
,
"record-type-opaque?":{
"filename":"root/biwascheme.js",
"line":5984,
"documentation":""}
,
"record-type-field-names":{
"filename":"root/biwascheme.js",
"line":5990,
"documentation":""}
,
"record-field-mutable?":{
"filename":"root/biwascheme.js",
"line":5996,
"documentation":""}
,
"raise":{
"filename":"root/biwascheme.js",
"line":6013,
"documentation":""}
,
"port?":{
"filename":"root/biwascheme.js",
"line":6090,
"documentation":""}
,
"textual-port?":{
"filename":"root/biwascheme.js",
"line":6094,
"documentation":""}
,
"binary-port?":{
"filename":"root/biwascheme.js",
"line":6098,
"documentation":""}
,
"close-port":{
"filename":"root/biwascheme.js",
"line":6107,
"documentation":""}
,
"call-with-port":{
"filename":"root/biwascheme.js",
"line":6113,
"documentation":""}
,
"call-with-string-output-port":{
"filename":"root/biwascheme.js",
"line":6162,
"documentation":""}
,
"make-custom-textual-output-port":{
"filename":"root/biwascheme.js",
"line":6180,
"documentation":""}
,
"put-char":{
"filename":"root/biwascheme.js",
"line":6194,
"documentation":""}
,
"put-string":{
"filename":"root/biwascheme.js",
"line":6200,
"documentation":""}
,
"put-datum":{
"filename":"root/biwascheme.js",
"line":6206,
"documentation":""}
,
"eof-object":{
"filename":"root/biwascheme.js",
"line":6218,
"documentation":""}
,
"eof-object?":{
"filename":"root/biwascheme.js",
"line":6221,
"documentation":""}
,
"input-port?":{
"filename":"root/biwascheme.js",
"line":6226,
"documentation":""}
,
"output-port?":{
"filename":"root/biwascheme.js",
"line":6230,
"documentation":""}
,
"current-input-port":{
"filename":"root/biwascheme.js",
"line":6234,
"documentation":""}
,
"current-output-port":{
"filename":"root/biwascheme.js",
"line":6237,
"documentation":""}
,
"current-error-port":{
"filename":"root/biwascheme.js",
"line":6240,
"documentation":""}
,
"close-input-port":{
"filename":"root/biwascheme.js",
"line":6247,
"documentation":""}
,
"close-output-port":{
"filename":"root/biwascheme.js",
"line":6254,
"documentation":""}
,
"read":{
"filename":"root/biwascheme.js",
"line":6263,
"documentation":""}
,
"write-char":{
"filename":"root/biwascheme.js",
"line":6274,
"documentation":""}
,
"newline":{
"filename":"root/biwascheme.js",
"line":6280,
"documentation":""}
,
"display":{
"filename":"root/biwascheme.js",
"line":6285,
"documentation":""}
,
"write":{
"filename":"root/biwascheme.js",
"line":6290,
"documentation":""}
,
"bitwise-not":{
"filename":"root/biwascheme.js",
"line":6410,
"documentation":""}
,
"bitwise-and":{
"filename":"root/biwascheme.js",
"line":6415,
"documentation":""}
,
"bitwise-ior":{
"filename":"root/biwascheme.js",
"line":6420,
"documentation":""}
,
"bitwise-xor":{
"filename":"root/biwascheme.js",
"line":6425,
"documentation":""}
,
"bitwise-if":{
"filename":"root/biwascheme.js",
"line":6430,
"documentation":""}
,
"bitwise-bit-count":{
"filename":"root/biwascheme.js",
"line":6435,
"documentation":""}
,
"bitwise-length":{
"filename":"root/biwascheme.js",
"line":6444,
"documentation":""}
,
"bitwise-first-bit-set":{
"filename":"root/biwascheme.js",
"line":6453,
"documentation":""}
,
"bitwise-bit-set?":{
"filename":"root/biwascheme.js",
"line":6463,
"documentation":""}
,
"bitwise-copy-bit":{
"filename":"root/biwascheme.js",
"line":6468,
"documentation":""}
,
"bitwise-bit-field":{
"filename":"root/biwascheme.js",
"line":6475,
"documentation":""}
,
"bitwise-copy-bit-field":{
"filename":"root/biwascheme.js",
"line":6481,
"documentation":""}
,
"bitwise-arithmetic-shift":{
"filename":"root/biwascheme.js",
"line":6490,
"documentation":""}
,
"bitwise-arithmetic-shift-left":{
"filename":"root/biwascheme.js",
"line":6495,
"documentation":""}
,
"bitwise-arithmetic-shift-right":{
"filename":"root/biwascheme.js",
"line":6500,
"documentation":""}
,
"bitwise-rotate-bit-field":{
"filename":"root/biwascheme.js",
"line":6505,
"documentation":""}
,
"bitwise-reverse-bit-field":{
"filename":"root/biwascheme.js",
"line":6521,
"documentation":""}
,
"make-eq-hashtable":{
"filename":"root/biwascheme.js",
"line":6544,
"documentation":""}
,
"make-eqv-hashtable":{
"filename":"root/biwascheme.js",
"line":6550,
"documentation":""}
,
"make-hashtable":{
"filename":"root/biwascheme.js",
"line":6555,
"documentation":""}
,
"hashtable?":{
"filename":"root/biwascheme.js",
"line":6563,
"documentation":""}
,
"hashtable-size":{
"filename":"root/biwascheme.js",
"line":6567,
"documentation":""}
,
"hashtable-ref":{
"filename":"root/biwascheme.js",
"line":6613,
"documentation":""}
,
"hashtable-set!":{
"filename":"root/biwascheme.js",
"line":6628,
"documentation":""}
,
"hashtable-delete!":{
"filename":"root/biwascheme.js",
"line":6646,
"documentation":""}
,
"hashtable-contains?":{
"filename":"root/biwascheme.js",
"line":6663,
"documentation":""}
,
"hashtable-update!":{
"filename":"root/biwascheme.js",
"line":6678,
"documentation":""}
,
"hashtable-copy":{
"filename":"root/biwascheme.js",
"line":6705,
"documentation":""}
,
"hashtable-clear!":{
"filename":"root/biwascheme.js",
"line":6712,
"documentation":""}
,
"hashtable-keys":{
"filename":"root/biwascheme.js",
"line":6719,
"documentation":""}
,
"hashtable-entries":{
"filename":"root/biwascheme.js",
"line":6724,
"documentation":""}
,
"hashtable-equivalence-function":{
"filename":"root/biwascheme.js",
"line":6732,
"documentation":""}
,
"hashtable-hash-function":{
"filename":"root/biwascheme.js",
"line":6737,
"documentation":""}
,
"hashtable-mutable?":{
"filename":"root/biwascheme.js",
"line":6742,
"documentation":""}
,
"equal-hash":{
"filename":"root/biwascheme.js",
"line":6750,
"documentation":""}
,
"string-hash":{
"filename":"root/biwascheme.js",
"line":6754,
"documentation":""}
,
"string-ci-hash":{
"filename":"root/biwascheme.js",
"line":6758,
"documentation":""}
,
"symbol-hash":{
"filename":"root/biwascheme.js",
"line":6762,
"documentation":""}
,
"make-enumeration":{
"filename":"root/biwascheme.js",
"line":6770,
"documentation":""}
,
"enum-set-universe":{
"filename":"root/biwascheme.js",
"line":6778,
"documentation":""}
,
"enum-set-indexer":{
"filename":"root/biwascheme.js",
"line":6784,
"documentation":""}
,
"enum-set-constructor":{
"filename":"root/biwascheme.js",
"line":6790,
"documentation":""}
,
"enum-set->list":{
"filename":"root/biwascheme.js",
"line":6796,
"documentation":""}
,
"enum-set-member?":{
"filename":"root/biwascheme.js",
"line":6802,
"documentation":""}
,
"enum-set-subset?":{
"filename":"root/biwascheme.js",
"line":6809,
"documentation":""}
,
"enum-set=?":{
"filename":"root/biwascheme.js",
"line":6816,
"documentation":""}
,
"enum-set-union":{
"filename":"root/biwascheme.js",
"line":6823,
"documentation":""}
,
"enum-set-intersection":{
"filename":"root/biwascheme.js",
"line":6832,
"documentation":""}
,
"enum-set-difference":{
"filename":"root/biwascheme.js",
"line":6839,
"documentation":""}
,
"enum-set-complement":{
"filename":"root/biwascheme.js",
"line":6846,
"documentation":""}
,
"enum-set-projection":{
"filename":"root/biwascheme.js",
"line":6852,
"documentation":""}
,
"eval":{
"filename":"root/biwascheme.js",
"line":6932,
"documentation":""}
,
"force":{
"filename":"root/biwascheme.js",
"line":7028,
"documentation":""}
,
"promise?":{
"filename":"root/biwascheme.js",
"line":7034,
"documentation":""}
,
"make-promise":{
"filename":"root/biwascheme.js",
"line":7039,
"documentation":""}
,
" procedure->promise":{
"filename":"root/biwascheme.js",
"line":7052,
"documentation":""}
,
"js-eval":{
"filename":"root/biwascheme.js",
"line":7062,
"documentation":""}
,
"js-ref":{
"filename":"root/biwascheme.js",
"line":7065,
"documentation":""}
,
"js-set!":{
"filename":"root/biwascheme.js",
"line":7074,
"documentation":""}
,
"js-call":{
"filename":"root/biwascheme.js",
"line":7081,
"documentation":""}
,
"js-invoke":{
"filename":"root/biwascheme.js",
"line":7089,
"documentation":""}
,
"js-invocation":{
"filename":"root/biwascheme.js",
"line":7117,
"documentation":""}
,
"js-new":{
"filename":"root/biwascheme.js",
"line":7189,
"documentation":""}
,
"js-obj":{
"filename":"root/biwascheme.js",
"line":7232,
"documentation":""}
,
"js-closure":{
"filename":"root/biwascheme.js",
"line":7256,
"documentation":""}
,
"js-null?":{
"filename":"root/biwascheme.js",
"line":7261,
"documentation":""}
,
"js-undefined?":{
"filename":"root/biwascheme.js",
"line":7265,
"documentation":""}
,
"js-function?":{
"filename":"root/biwascheme.js",
"line":7269,
"documentation":""}
,
"js-array-to-list":{
"filename":"root/biwascheme.js",
"line":7273,
"documentation":""}
,
"js-array->list":{
"filename":"root/biwascheme.js",
"line":7278,
"documentation":""}
,
"list-to-js-array":{
"filename":"root/biwascheme.js",
"line":7282,
"documentation":""}
,
"list->js-array":{
"filename":"root/biwascheme.js",
"line":7287,
"documentation":""}
,
"alist-to-js-obj":{
"filename":"root/biwascheme.js",
"line":7303,
"documentation":""}
,
"alist->js-obj":{
"filename":"root/biwascheme.js",
"line":7308,
"documentation":""}
,
"js-obj-to-alist":{
"filename":"root/biwascheme.js",
"line":7323,
"documentation":""}
,
"js-obj->alist":{
"filename":"root/biwascheme.js",
"line":7327,
"documentation":""}
,
"timer":{
"filename":"root/biwascheme.js",
"line":7334,
"documentation":""}
,
"set-timer!":{
"filename":"root/biwascheme.js",
"line":7342,
"documentation":""}
,
"clear-timer!":{
"filename":"root/biwascheme.js",
"line":7349,
"documentation":""}
,
"sleep":{
"filename":"root/biwascheme.js",
"line":7354,
"documentation":""}
,
"console-+name":{
"filename":"root/biwascheme.js",
"line":7376,
"documentation":""}
,
"html-escape":{
"filename":"root/biwascheme.js",
"line":7397,
"documentation":""}
,
"inspect":{
"filename":"root/biwascheme.js",
"line":7404,
"documentation":""}
,
"inspect!":{
"filename":"root/biwascheme.js",
"line":7407,
"documentation":""}
,
"json->sexp":{
"filename":"root/biwascheme.js",
"line":7440,
"documentation":""}
,
"vector-push!":{
"filename":"root/biwascheme.js",
"line":7445,
"documentation":""}
,
"identity":{
"filename":"root/biwascheme.js",
"line":7459,
"documentation":""}
,
"string-concat":{
"filename":"root/biwascheme.js",
"line":7489,
"documentation":""}
,
"string-split":{
"filename":"root/biwascheme.js",
"line":7494,
"documentation":""}
,
"string-join":{
"filename":"root/biwascheme.js",
"line":7500,
"documentation":""}
,
"intersperse":{
"filename":"root/biwascheme.js",
"line":7512,
"documentation":""}
,
"map-with-index":{
"filename":"root/biwascheme.js",
"line":7525,
"documentation":""}
,
"list-sort/comp":{
"filename":"root/biwascheme.js",
"line":7580,
"documentation":""}
,
"vector-sort/comp":{
"filename":"root/biwascheme.js",
"line":7586,
"documentation":""}
,
"vector-sort/comp!":{
"filename":"root/biwascheme.js",
"line":7592,
"documentation":""}
,
"macroexpand":{
"filename":"root/biwascheme.js",
"line":7675,
"documentation":""}
,
"macroexpand-1":{
"filename":"root/biwascheme.js",
"line":7678,
"documentation":""}
,
"gensym":{
"filename":"root/biwascheme.js",
"line":7682,
"documentation":""}
,
"print":{
"filename":"root/biwascheme.js",
"line":7688,
"documentation":""}
,
"write-to-string":{
"filename":"root/biwascheme.js",
"line":7695,
"documentation":""}
,
"read-from-string":{
"filename":"root/biwascheme.js",
"line":7698,
"documentation":""}
,
"port-closed?":{
"filename":"root/biwascheme.js",
"line":7702,
"documentation":""}
,
"with-input-from-port":{
"filename":"root/biwascheme.js",
"line":7706,
"documentation":""}
,
"with-error-to-port":{
"filename":"root/biwascheme.js",
"line":7707,
"documentation":""}
,
"with-output-to-port":{
"filename":"root/biwascheme.js",
"line":7708,
"documentation":""}
,
"string->regexp":{
"filename":"root/biwascheme.js",
"line":7748,
"documentation":""}
,
"regexp?":{
"filename":"string/string-extensions.js",
"line":157,
"documentation":""}
,
"regexp->string":{
"filename":"root/biwascheme.js",
"line":7757,
"documentation":""}
,
"regexp-exec":{
"filename":"root/biwascheme.js",
"line":7762,
"documentation":""}
,
"rxmatch":{
"filename":"root/biwascheme.js",
"line":7774,
"documentation":""}
,
"regexp-replace-all":{
"filename":"root/biwascheme.js",
"line":7791,
"documentation":""}
,
"iota":{
"filename":"root/biwascheme.js",
"line":7917,
"documentation":""}
,
"list-copy":{
"filename":"root/biwascheme.js",
"line":7941,
"documentation":""}
,
"open-input-string":{
"filename":"root/biwascheme.js",
"line":7953,
"documentation":""}
,
"open-output-string":{
"filename":"root/biwascheme.js",
"line":7957,
"documentation":""}
,
"get-output-string":{
"filename":"root/biwascheme.js",
"line":7960,
"documentation":""}
,
"current-date":{
"filename":"root/biwascheme.js",
"line":8000,
"documentation":""}
,
"date?":{
"filename":"root/biwascheme.js",
"line":8034,
"documentation":""}
,
"date-nanosecond":{
"filename":"root/biwascheme.js",
"line":8037,
"documentation":""}
,
"date-millisecond":{
"filename":"root/biwascheme.js",
"line":8041,
"documentation":""}
,
"date-second":{
"filename":"root/biwascheme.js",
"line":8045,
"documentation":""}
,
"date-minute":{
"filename":"root/biwascheme.js",
"line":8049,
"documentation":""}
,
"date-hour":{
"filename":"root/biwascheme.js",
"line":8053,
"documentation":""}
,
"date-day":{
"filename":"root/biwascheme.js",
"line":8057,
"documentation":""}
,
"date-month":{
"filename":"root/biwascheme.js",
"line":8061,
"documentation":""}
,
"date-year":{
"filename":"root/biwascheme.js",
"line":8065,
"documentation":""}
,
"date-week-day":{
"filename":"root/biwascheme.js",
"line":8071,
"documentation":""}
,
"date->string":{
"filename":"root/biwascheme.js",
"line":8156,
"documentation":""}
,
"parse-date":{
"filename":"root/biwascheme.js",
"line":8169,
"documentation":""}
,
"random-integer":{
"filename":"root/biwascheme.js",
"line":8177,
"documentation":""}
,
"random-real":{
"filename":"root/biwascheme.js",
"line":8185,
"documentation":""}
,
"format":{
"filename":"root/biwascheme.js",
"line":8201,
"documentation":""}
,
"write/ss":{
"filename":"root/biwascheme.js",
"line":8244,
"documentation":""}
,
"write-with-shared-structure":{
"filename":"root/biwascheme.js",
"line":8245,
"documentation":""}
,
"write*":{
"filename":"root/biwascheme.js",
"line":8246,
"documentation":""}
,
"vector-append":{
"filename":"root/biwascheme.js",
"line":8251,
"documentation":""}
,
"vector-copy":{
"filename":"root/biwascheme.js",
"line":8257,
"documentation":""}
,
"read-line":{
"filename":"root/biwascheme.js",
"line":8269,
"documentation":""}
,
"element-empty!":{
"filename":"root/biwascheme.js",
"line":8278,
"documentation":""}
,
"element-visible?":{
"filename":"root/biwascheme.js",
"line":8286,
"documentation":""}
,
"element-toggle!":{
"filename":"root/biwascheme.js",
"line":8289,
"documentation":""}
,
"element-hide!":{
"filename":"root/biwascheme.js",
"line":8292,
"documentation":""}
,
"element-show!":{
"filename":"root/biwascheme.js",
"line":8295,
"documentation":""}
,
"element-remove!":{
"filename":"root/biwascheme.js",
"line":8298,
"documentation":""}
,
"element-update!":{
"filename":"root/biwascheme.js",
"line":8301,
"documentation":""}
,
"element-replace!":{
"filename":"root/biwascheme.js",
"line":8304,
"documentation":""}
,
"element-insert!":{
"filename":"root/biwascheme.js",
"line":8307,
"documentation":""}
,
"element-wrap!":{
"filename":"root/biwascheme.js",
"line":8310,
"documentation":""}
,
"element-ancestors":{
"filename":"root/biwascheme.js",
"line":8313,
"documentation":""}
,
"element-descendants":{
"filename":"root/biwascheme.js",
"line":8316,
"documentation":""}
,
"element-first-descendant":{
"filename":"root/biwascheme.js",
"line":8319,
"documentation":""}
,
"element-immediate-descendants":{
"filename":"root/biwascheme.js",
"line":8322,
"documentation":""}
,
"element-previous-sibling":{
"filename":"root/biwascheme.js",
"line":8325,
"documentation":""}
,
"element-next-sibling":{
"filename":"root/biwascheme.js",
"line":8328,
"documentation":""}
,
"element-siblings":{
"filename":"root/biwascheme.js",
"line":8331,
"documentation":""}
,
"element-match?":{
"filename":"root/biwascheme.js",
"line":8334,
"documentation":""}
,
"element-up":{
"filename":"root/biwascheme.js",
"line":8337,
"documentation":""}
,
"element-down":{
"filename":"root/biwascheme.js",
"line":8340,
"documentation":""}
,
"element-previous":{
"filename":"root/biwascheme.js",
"line":8343,
"documentation":""}
,
"element-next":{
"filename":"root/biwascheme.js",
"line":8346,
"documentation":""}
,
"element-select":{
"filename":"root/biwascheme.js",
"line":8349,
"documentation":""}
,
"element-adjacent":{
"filename":"root/biwascheme.js",
"line":8352,
"documentation":""}
,
"element-identify":{
"filename":"root/biwascheme.js",
"line":8355,
"documentation":""}
,
"element-read-attribute":{
"filename":"root/biwascheme.js",
"line":8358,
"documentation":""}
,
"element-write-attribute":{
"filename":"root/biwascheme.js",
"line":8367,
"documentation":""}
,
"element-write-attribute!":{
"filename":"root/biwascheme.js",
"line":8372,
"documentation":""}
,
"element-height":{
"filename":"root/biwascheme.js",
"line":8374,
"documentation":""}
,
"element-width":{
"filename":"root/biwascheme.js",
"line":8377,
"documentation":""}
,
"element-class-names":{
"filename":"root/biwascheme.js",
"line":8381,
"documentation":""}
,
"element-has-class-name?":{
"filename":"root/biwascheme.js",
"line":8384,
"documentation":""}
,
"element-add-class-name":{
"filename":"root/biwascheme.js",
"line":8393,
"documentation":""}
,
"element-add-class-name!":{
"filename":"root/biwascheme.js",
"line":8398,
"documentation":""}
,
"element-remove-class-name":{
"filename":"root/biwascheme.js",
"line":8404,
"documentation":""}
,
"element-remove-class-name!":{
"filename":"root/biwascheme.js",
"line":8409,
"documentation":""}
,
"element-toggle-class-name":{
"filename":"root/biwascheme.js",
"line":8415,
"documentation":""}
,
"element-toggle-class-name!":{
"filename":"root/biwascheme.js",
"line":8420,
"documentation":""}
,
"element-clean-whitespace!":{
"filename":"root/biwascheme.js",
"line":8422,
"documentation":""}
,
"element-empty?":{
"filename":"root/biwascheme.js",
"line":8425,
"documentation":""}
,
"element-descendant-of!":{
"filename":"root/biwascheme.js",
"line":8428,
"documentation":""}
,
"scroll-to-element!":{
"filename":"root/biwascheme.js",
"line":8431,
"documentation":""}
,
"element-style":{
"filename":"root/biwascheme.js",
"line":8434,
"documentation":""}
,
"element-opacity":{
"filename":"root/biwascheme.js",
"line":8437,
"documentation":""}
,
"element-style-set!":{
"filename":"root/biwascheme.js",
"line":8440,
"documentation":""}
,
"element-opacity-set!":{
"filename":"root/biwascheme.js",
"line":8443,
"documentation":""}
,
"element-dimensions":{
"filename":"root/biwascheme.js",
"line":8446,
"documentation":""}
,
"element-make-positioned!":{
"filename":"root/biwascheme.js",
"line":8449,
"documentation":""}
,
"element-undo-positioned!":{
"filename":"root/biwascheme.js",
"line":8452,
"documentation":""}
,
"element-make-clipping!":{
"filename":"root/biwascheme.js",
"line":8455,
"documentation":""}
,
"element-undo-clipping!":{
"filename":"root/biwascheme.js",
"line":8458,
"documentation":""}
,
"element-cumulative-offset":{
"filename":"root/biwascheme.js",
"line":8461,
"documentation":""}
,
"element-positioned-offset":{
"filename":"root/biwascheme.js",
"line":8464,
"documentation":""}
,
"element-absolutize!":{
"filename":"root/biwascheme.js",
"line":8485,
"documentation":""}
,
"element-relativize!":{
"filename":"root/biwascheme.js",
"line":8470,
"documentation":""}
,
"element-cumulative-scroll-offset":{
"filename":"root/biwascheme.js",
"line":8473,
"documentation":""}
,
"element-offset-parent":{
"filename":"root/biwascheme.js",
"line":8476,
"documentation":""}
,
"element-viewport-offset":{
"filename":"root/biwascheme.js",
"line":8479,
"documentation":""}
,
"element-clone-position!":{
"filename":"root/biwascheme.js",
"line":8482,
"documentation":""}
,
"element-focus!":{
"filename":"root/biwascheme.js",
"line":8488,
"documentation":""}
,
"element-new":{
"filename":"root/biwascheme.js",
"line":8542,
"documentation":""}
,
"element-content":{
"filename":"root/biwascheme.js",
"line":8561,
"documentation":""}
,
"load":{
"filename":"root/biwascheme.js",
"line":8568,
"documentation":""}
,
"js-load":{
"filename":"root/biwascheme.js",
"line":8601,
"documentation":""}
,
"$":{
"filename":"root/biwascheme.js",
"line":8631,
"documentation":""}
,
"getelem":{
"filename":"root/biwascheme.js",
"line":8632,
"documentation":""}
,
"dom-element":{
"filename":"root/biwascheme.js",
"line":8633,
"documentation":""}
,
"set-style!":{
"filename":"root/biwascheme.js",
"line":8637,
"documentation":""}
,
"get-style":{
"filename":"root/biwascheme.js",
"line":8642,
"documentation":""}
,
"set-content!":{
"filename":"root/biwascheme.js",
"line":8646,
"documentation":""}
,
"get-content":{
"filename":"root/biwascheme.js",
"line":8652,
"documentation":""}
,
"set-handler!":{
"filename":"root/biwascheme.js",
"line":8659,
"documentation":""}
,
"add-handler!":{
"filename":"root/biwascheme.js",
"line":8662,
"documentation":""}
,
"remove-handler!":{
"filename":"root/biwascheme.js",
"line":8671,
"documentation":""}
,
"wait-for":{
"filename":"root/biwascheme.js",
"line":8676,
"documentation":""}
,
"domelem":{
"filename":"root/biwascheme.js",
"line":8703,
"documentation":""}
,
"dom-remove-children!":{
"filename":"root/biwascheme.js",
"line":8706,
"documentation":""}
,
"dom-create-element":{
"filename":"root/biwascheme.js",
"line":8711,
"documentation":""}
,
"element-append-child!":{
"filename":"root/biwascheme.js",
"line":8714,
"documentation":""}
,
"dom-remove-child!":{
"filename":"root/biwascheme.js",
"line":8722,
"documentation":""}
,
"dom-get-attribute":{
"filename":"root/biwascheme.js",
"line":8720,
"documentation":""}
,
"http-request":{
"filename":"root/biwascheme.js",
"line":8728,
"documentation":""}
,
"http-post":{
"filename":"root/biwascheme.js",
"line":8739,
"documentation":""}
,
"receive-jsonp":{
"filename":"root/biwascheme.js",
"line":8754,
"documentation":""}
,
"alert":{
"filename":"root/biwascheme.js",
"line":8777,
"documentation":""}
,
"confirm":{
"filename":"root/biwascheme.js",
"line":8781,
"documentation":""}
,
"dumpobj":{
"filename":"root/biwascheme.js",
"line":8784,
"documentation":""}
,
"clear-cumulative-errors":{
"filename":"root/system-extensions.js",
"line":21,
"documentation":""}
,
"cumulative-errors":{
"filename":"root/system-extensions.js",
"line":27,
"documentation":""}
,
"enumerate-procedures":{
"filename":"root/system-extensions.js",
"line":32,
"documentation":""}
,
"is-alist?":{
"filename":"root/system-extensions.js",
"line":37,
"documentation":""}
,
"is-dotted-pair?":{
"filename":"root/system-extensions.js",
"line":42,
"documentation":""}
,
"is-procedure-defined?":{
"filename":"root/system-extensions.js",
"line":47,
"documentation":""}
,
"js-biwa-evaluate":{
"filename":"root/system-extensions.js",
"line":77,
"documentation":""}
,
"repl-here":{
"filename":"root/system-extensions.js",
"line":91,
"documentation":""}
,
"string-reader":{
"filename":"root/system-extensions.js",
"line":100,
"documentation":""}
,
"string-reader-read":{
"filename":"root/system-extensions.js",
"line":106,
"documentation":""}
,
"save-the-static-world":{
"filename":"root/root-utilities.scm",
"line":6,
"documentation":""}
,
"clone-workspace":{
"filename":"root/root-utilities.scm",
"line":9,
"documentation":""}
,
"process-template-lines":{
"filename":"root/root-utilities.scm",
"line":16,
"documentation":""}
,
"uuid ":{
"filename":"root/uuid-extensions.js",
"line":4,
"documentation":""}
,
"no-dash-uuid ":{
"filename":"root/uuid-extensions.js",
"line":9,
"documentation":""}
,
"":{
"filename":"documentation/documentation-extensions.js",
"line":12,
"documentation":""}
,
"export-documentation":{
"filename":"documentation/documentation-extensions.js",
"line":70,
"documentation":""}
,
"rebuild-documentation":{
"filename":"documentation/documentation-extensions.js",
"line":74,
"documentation":""}
,
"retrieve-procedure-definition":{
"filename":"documentation/documentation-extensions.js",
"line":93,
"documentation":""}
,
"enumerate-undocumented-procedures":{
"filename":"documentation/documentation-extensions.js",
"line":135,
"documentation":""}
,
"fronkensteen-documentation-procedure-field":{
"filename":"documentation/documentation-ui.scm",
"line":0,
"documentation":""}
,
"fronkensteen-documentation-documentation-field":{
"filename":"documentation/documentation-ui.scm",
"line":12,
"documentation":""}
,
"fronkensteen-documentation-definition-area":{
"filename":"documentation/documentation-ui.scm",
"line":16,
"documentation":""}
,
"clear-local-storage!":{
"filename":"browser/browser-extensions.js",
"line":7,
"documentation":""}
,
"get-local-storage-item":{
"filename":"browser/browser-extensions.js",
"line":13,
"documentation":""}
,
"window-location-href":{
"filename":"browser/browser-extensions.js",
"line":24,
"documentation":""}
,
"navigate":{
"filename":"browser/browser-extensions.js",
"line":28,
"documentation":""}
,
"prompt":{
"filename":"browser/browser-extensions.js",
"line":35,
"documentation":""}
,
"reload":{
"filename":"browser/browser-extensions.js",
"line":43,
"documentation":""}
,
"remove-local-storage-item!":{
"filename":"browser/browser-extensions.js",
"line":48,
"documentation":""}
,
"scroll-to-bottom":{
"filename":"browser/browser-extensions.js",
"line":55,
"documentation":""}
,
"scroll-to-top":{
"filename":"browser/browser-extensions.js",
"line":63,
"documentation":""}
,
"set-local-storage-item!":{
"filename":"browser/browser-extensions.js",
"line":69,
"documentation":""}
,
"write-to-clipboard!":{
"filename":"browser/browser-extensions.js",
"line":77,
"documentation":""}
,
"get-file-tree":{
"filename":"filesystem/filesystem-extensions.js",
"line":205,
"documentation":""}
,
"get-file-names":{
"filename":"filesystem/filesystem-extensions.js",
"line":210,
"documentation":""}
,
"get-bales":{
"filename":"filesystem/filesystem-extensions.js",
"line":215,
"documentation":""}
,
"remove-bale":{
"filename":"filesystem/filesystem-extensions.js",
"line":219,
"documentation":""}
,
"get-internal-filesystem-json":{
"filename":"filesystem/filesystem-extensions.js",
"line":225,
"documentation":""}
,
"get-internal-dir":{
"filename":"filesystem/filesystem-extensions.js",
"line":229,
"documentation":""}
,
"file-extension":{
"filename":"filesystem/filesystem-extensions.js",
"line":235,
"documentation":""}
,
"file-basename":{
"filename":"filesystem/filesystem-extensions.js",
"line":241,
"documentation":""}
,
"file-path":{
"filename":"filesystem/filesystem-extensions.js",
"line":246,
"documentation":""}
,
"file-basename-no-extension":{
"filename":"filesystem/filesystem-extensions.js",
"line":252,
"documentation":""}
,
"file-name-no-extension":{
"filename":"filesystem/filesystem-extensions.js",
"line":258,
"documentation":""}
,
"bytes-to-base-64-image":{
"filename":"filesystem/filesystem-extensions.js",
"line":263,
"documentation":""}
,
"base-64-image-to-bytes":{
"filename":"filesystem/filesystem-extensions.js",
"line":269,
"documentation":""}
,
"download-text-file":{
"filename":"filesystem/filesystem-extensions.js",
"line":276,
"documentation":""}
,
"delete-internal-file":{
"filename":"filesystem/filesystem-extensions.js",
"line":284,
"documentation":""}
,
"read-internal-data-url":{
"filename":"filesystem/filesystem-extensions.js",
"line":291,
"documentation":""}
,
"write-internal-file":{
"filename":"filesystem/filesystem-extensions.js",
"line":296,
"documentation":""}
,
"read-internal-text-file":{
"filename":"filesystem/filesystem-extensions.js",
"line":302,
"documentation":""}
,
"write-internal-text-file":{
"filename":"filesystem/filesystem-extensions.js",
"line":308,
"documentation":""}
,
"hereload":{
"filename":"filesystem/filesystem-extensions.js",
"line":313,
"documentation":""}
,
"mime-type ":{
"filename":"filesystem/filetypes-extensions.js",
"line":4,
"documentation":""}
,
"reset-block-db!":{
"filename":"blocks/blocks.scm",
"line":8,
"documentation":""}
,
"set-collection!":{
"filename":"blocks/blocks.scm",
"line":14,
"documentation":""}
,
"get-collection":{
"filename":"blocks/blocks.scm",
"line":22,
"documentation":""}
,
"add-block-to-collection!":{
"filename":"blocks/blocks.scm",
"line":26,
"documentation":""}
,
"find-next-block":{
"filename":"blocks/blocks.scm",
"line":34,
"documentation":""}
,
"find-previous-block":{
"filename":"blocks/blocks.scm",
"line":42,
"documentation":""}
,
"get-next-block":{
"filename":"blocks/blocks.scm",
"line":48,
"documentation":""}
,
"get-previous-block":{
"filename":"blocks/blocks.scm",
"line":52,
"documentation":""}
,
"title-in-collection?":{
"filename":"blocks/blocks.scm",
"line":56,
"documentation":""}
,
"title-in-block-list?":{
"filename":"blocks/blocks.scm",
"line":62,
"documentation":""}
,
"enumerate-collection-ids-titles":{
"filename":"blocks/blocks.scm",
"line":67,
"documentation":""}
,
"enumerate-collection-titles":{
"filename":"blocks/blocks.scm",
"line":73,
"documentation":""}
,
"enumerate-block-list-titles":{
"filename":"blocks/blocks.scm",
"line":80,
"documentation":""}
,
"enumerate-block-list-ids-titles":{
"filename":"blocks/blocks.scm",
"line":86,
"documentation":""}
,
"append-block-to-collection!":{
"filename":"blocks/blocks.scm",
"line":93,
"documentation":""}
,
"prepend-block-to-collection!":{
"filename":"blocks/blocks.scm",
"line":102,
"documentation":""}
,
"add-block-to-db!":{
"filename":"blocks/blocks.scm",
"line":111,
"documentation":""}
,
"get-block":{
"filename":"blocks/blocks.scm",
"line":117,
"documentation":""}
,
"clone-block":{
"filename":"blocks/blocks.scm",
"line":121,
"documentation":""}
,
"clone-block-elements":{
"filename":"blocks/blocks.scm",
"line":131,
"documentation":""}
,
"new-block!":{
"filename":"blocks/blocks.scm",
"line":136,
"documentation":""}
,
"new-collection-block!":{
"filename":"blocks/blocks.scm",
"line":140,
"documentation":""}
,
"set-block-param!":{
"filename":"blocks/blocks.scm",
"line":144,
"documentation":""}
,
"del-assq":{
"filename":"blocks/blocks.scm",
"line":154,
"documentation":""}
,
"get-block-param":{
"filename":"blocks/blocks.scm",
"line":159,
"documentation":""}
,
"update-block-title!":{
"filename":"blocks/blocks.scm",
"line":170,
"documentation":""}
,
"update-block-content!":{
"filename":"blocks/blocks.scm",
"line":173,
"documentation":""}
,
"update-block-title-and-content!":{
"filename":"blocks/blocks.scm",
"line":177,
"documentation":""}
,
"get-block-title":{
"filename":"blocks/blocks.scm",
"line":182,
"documentation":""}
,
"get-block-content":{
"filename":"blocks/blocks.scm",
"line":186,
"documentation":""}
,
"get-block-type":{
"filename":"blocks/blocks.scm",
"line":189,
"documentation":""}
,
"block-match?":{
"filename":"blocks/blocks.scm",
"line":192,
"documentation":""}
,
"block-text-search-rec":{
"filename":"blocks/blocks.scm",
"line":198,
"documentation":""}
,
"block-text-search":{
"filename":"blocks/blocks.scm",
"line":207,
"documentation":""}
,
"set-block-indent!":{
"filename":"blocks/blocks.scm",
"line":212,
"documentation":""}
,
"get-block-indent":{
"filename":"blocks/blocks.scm",
"line":217,
"documentation":""}
,
"delete-block!":{
"filename":"blocks/blocks.scm",
"line":220,
"documentation":""}
,
"delete-block-id-from-list-rec!":{
"filename":"blocks/blocks.scm",
"line":223,
"documentation":""}
,
"delete-block-from-collection!":{
"filename":"blocks/blocks.scm",
"line":228,
"documentation":""}
,
"insert-block-id-in-list-after-rec!":{
"filename":"blocks/blocks.scm",
"line":235,
"documentation":""}
,
"insert-block-id-in-collection-after!":{
"filename":"blocks/blocks.scm",
"line":241,
"documentation":""}
,
"is-block-in-list?":{
"filename":"blocks/blocks.scm",
"line":247,
"documentation":""}
,
"is-block-in-collection?":{
"filename":"blocks/blocks.scm",
"line":252,
"documentation":""}
,
"transfer-collection!":{
"filename":"blocks/blocks.scm",
"line":255,
"documentation":""}
,
"iso-8601-date":{
"filename":"date-time/date-time-extensions.js",
"line":5,
"documentation":""}
,
"iso-8601-date-epub-3":{
"filename":"date-time/date-time-extensions.js",
"line":10,
"documentation":""}
,
"iso-8601-date-short":{
"filename":"date-time/date-time-extensions.js",
"line":16,
"documentation":""}
,
"unix-time":{
"filename":"date-time/date-time-extensions.js",
"line":22,
"documentation":""}
,
"encode-uri":{
"filename":"string/string-extensions.js",
"line":12,
"documentation":""}
,
"encode-uri-component":{
"filename":"string/string-extensions.js",
"line":17,
"documentation":""}
,
"decode-uri":{
"filename":"string/string-extensions.js",
"line":23,
"documentation":""}
,
"decode-uri-component":{
"filename":"string/string-extensions.js",
"line":28,
"documentation":""}
,
"escape-html":{
"filename":"string/string-extensions.js",
"line":34,
"documentation":""}
,
"indexOf":{
"filename":"string/string-extensions.js",
"line":41,
"documentation":""}
,
"str-escape":{
"filename":"string/string-extensions.js",
"line":48,
"documentation":""}
,
"str-find":{
"filename":"string/string-extensions.js",
"line":54,
"documentation":""}
,
"str-find-unique":{
"filename":"string/string-extensions.js",
"line":68,
"documentation":""}
,
"str-match?":{
"filename":"string/string-extensions.js",
"line":82,
"documentation":""}
,
"str-replace":{
"filename":"string/string-extensions.js",
"line":96,
"documentation":""}
,
"str-replace-re":{
"filename":"string/string-extensions.js",
"line":107,
"documentation":""}
,
"str-split":{
"filename":"string/string-extensions.js",
"line":117,
"documentation":""}
,
"str-unescape":{
"filename":"string/string-extensions.js",
"line":123,
"documentation":""}
,
"str-trim":{
"filename":"string/string-extensions.js",
"line":129,
"documentation":""}
,
"str-wordcount":{
"filename":"string/string-extensions.js",
"line":136,
"documentation":""}
,
"make-regexp":{
"filename":"string/string-extensions.js",
"line":147,
"documentation":""}
,
"reset-mla-level-counter":{
"filename":"string/string-utilities.scm",
"line":10,
"documentation":""}
,
"reset-lower-levels":{
"filename":"string/string-utilities.scm",
"line":14,
"documentation":""}
,
"mla-heading-string":{
"filename":"string/string-utilities.scm",
"line":21,
"documentation":""}
,
"convert-roman":{
"filename":"string/string-utilities.scm",
"line":38,
"documentation":""}
,
"convert-roman-helper":{
"filename":"string/string-utilities.scm",
"line":48,
"documentation":""}
,
"lower-case-letter-equivalent":{
"filename":"string/string-utilities.scm",
"line":60,
"documentation":""}
,
"upper-case-letter-equivalent":{
"filename":"string/string-utilities.scm",
"line":65,
"documentation":""}
,
"nth":{
"filename":"list-utilities/list-utilities.scm",
"line":4,
"documentation":""}
,
"nth-cdr":{
"filename":"list-utilities/list-utilities.scm",
"line":10,
"documentation":""}
,
"replace-nth":{
"filename":"list-utilities/list-utilities.scm",
"line":17,
"documentation":""}
,
"insert-nth":{
"filename":"list-utilities/list-utilities.scm",
"line":22,
"documentation":""}
,
"delete-nth":{
"filename":"list-utilities/list-utilities.scm",
"line":27,
"documentation":""}
,
"get-id-vector":{
"filename":"dom/dom-extensions.js",
"line":7,
"documentation":""}
,
"load-iframe":{
"filename":"dom/dom-extensions.js",
"line":24,
"documentation":""}
,
"attr":{
"filename":"dom/dom-extensions.js",
"line":34,
"documentation":""}
,
"attr!":{
"filename":"dom/dom-extensions.js",
"line":41,
"documentation":""}
,
"css":{
"filename":"dom/dom-extensions.js",
"line":51,
"documentation":""}
,
"css!":{
"filename":"dom/dom-extensions.js",
"line":59,
"documentation":""}
,
"get-selected-index":{
"filename":"dom/dom-extensions.js",
"line":69,
"documentation":""}
,
"disable!":{
"filename":"dom/dom-extensions.js",
"line":76,
"documentation":""}
,
"element-exists?":{
"filename":"dom/dom-extensions.js",
"line":84,
"documentation":""}
,
"js-install-head":{
"filename":"dom/dom-extensions.js",
"line":93,
"documentation":""}
,
"js-window-height":{
"filename":"dom/dom-extensions.js",
"line":99,
"documentation":""}
,
"js-window-width":{
"filename":"dom/dom-extensions.js",
"line":104,
"documentation":""}
,
"%":{
"filename":"dom/dom-extensions.js",
"line":109,
"documentation":""}
,
"prop":{
"filename":"dom/dom-extensions.js",
"line":133,
"documentation":""}
,
"prop!":{
"filename":"dom/dom-extensions.js",
"line":141,
"documentation":""}
,
"elems ":{
"filename":"dom/dom-extensions.js",
"line":151,
"documentation":""}
,
"sort-order ":{
"filename":"dom/dom-extensions.js",
"line":157,
"documentation":""}
,
"place-caret-at-start ":{
"filename":"dom/dom-extensions.js",
"line":188,
"documentation":""}
,
"place-caret-at-end ":{
"filename":"dom/dom-extensions.js",
"line":197,
"documentation":""}
,
"set-selected-index!":{
"filename":"dom/dom-extensions.js",
"line":208,
"documentation":""}
,
"jq-attr":{
"filename":"dom/dom-extensions.js",
"line":218,
"documentation":""}
,
"jq-is-empty-object?":{
"filename":"dom/dom-extensions.js",
"line":227,
"documentation":""}
,
"jq-length":{
"filename":"dom/dom-extensions.js",
"line":232,
"documentation":""}
,
"parse-seml":{
"filename":"dom/seml-extensions.js",
"line":182,
"documentation":""}
,
"set-content-editable-change-handler! ":{
"filename":"dom/content-editable-extensions.js",
"line":5,
"documentation":""}
,
"set-content-editable-save-handler! ":{
"filename":"dom/content-editable-extensions.js",
"line":12,
"documentation":""}
,
"sortable ":{
"filename":"dom/sortable-extensions.js",
"line":5,
"documentation":""}
,
"html-error":{
"filename":"dom/scheme-dom.scm",
"line":6,
"documentation":""}
,
"gen-id":{
"filename":"dom/scheme-dom.scm",
"line":11,
"documentation":""}
,
"seml-element":{
"filename":"dom/scheme-dom.scm",
"line":27,
"documentation":""}
,
"seml-self-closing-element":{
"filename":"dom/scheme-dom.scm",
"line":32,
"documentation":""}
,
"seml":{
"filename":"dom/scheme-dom.scm",
"line":37,
"documentation":""}
,
"seml-self-closing":{
"filename":"dom/scheme-dom.scm",
"line":45,
"documentation":""}
,
"!DOCTYPE":{
"filename":"dom/scheme-dom.scm",
"line":67,
"documentation":""}
,
"DOCTYPE":{
"filename":"dom/scheme-dom.scm",
"line":72,
"documentation":""}
,
"a":{
"filename":"dom/scheme-dom.scm",
"line":75,
"documentation":""}
,
"abbr":{
"filename":"dom/scheme-dom.scm",
"line":78,
"documentation":""}
,
"acronym":{
"filename":"dom/scheme-dom.scm",
"line":81,
"documentation":""}
,
"address":{
"filename":"dom/scheme-dom.scm",
"line":84,
"documentation":""}
,
"applet":{
"filename":"dom/scheme-dom.scm",
"line":87,
"documentation":""}
,
"area":{
"filename":"dom/scheme-dom.scm",
"line":90,
"documentation":""}
,
"article":{
"filename":"dom/scheme-dom.scm",
"line":93,
"documentation":""}
,
"aside":{
"filename":"dom/scheme-dom.scm",
"line":96,
"documentation":""}
,
"audio":{
"filename":"dom/scheme-dom.scm",
"line":99,
"documentation":""}
,
"b":{
"filename":"dom/scheme-dom.scm",
"line":102,
"documentation":""}
,
"base":{
"filename":"dom/scheme-dom.scm",
"line":105,
"documentation":""}
,
"bdi":{
"filename":"dom/scheme-dom.scm",
"line":108,
"documentation":""}
,
"bdo":{
"filename":"dom/scheme-dom.scm",
"line":111,
"documentation":""}
,
"blockquote":{
"filename":"dom/scheme-dom.scm",
"line":114,
"documentation":""}
,
"body":{
"filename":"dom/scheme-dom.scm",
"line":117,
"documentation":""}
,
"br":{
"filename":"dom/scheme-dom.scm",
"line":120,
"documentation":""}
,
"button":{
"filename":"dom/scheme-dom.scm",
"line":123,
"documentation":""}
,
"canvas":{
"filename":"dom/scheme-dom.scm",
"line":126,
"documentation":""}
,
"caption":{
"filename":"dom/scheme-dom.scm",
"line":129,
"documentation":""}
,
"cite":{
"filename":"dom/scheme-dom.scm",
"line":132,
"documentation":""}
,
"code":{
"filename":"dom/scheme-dom.scm",
"line":135,
"documentation":""}
,
"col":{
"filename":"dom/scheme-dom.scm",
"line":138,
"documentation":""}
,
"colgroup":{
"filename":"dom/scheme-dom.scm",
"line":141,
"documentation":""}
,
"command":{
"filename":"dom/scheme-dom.scm",
"line":144,
"documentation":""}
,
"datalist":{
"filename":"dom/scheme-dom.scm",
"line":147,
"documentation":""}
,
"dd":{
"filename":"dom/scheme-dom.scm",
"line":150,
"documentation":""}
,
"del":{
"filename":"dom/scheme-dom.scm",
"line":153,
"documentation":""}
,
"details":{
"filename":"dom/scheme-dom.scm",
"line":156,
"documentation":""}
,
"dfn":{
"filename":"dom/scheme-dom.scm",
"line":159,
"documentation":""}
,
"dv":{
"filename":"dom/scheme-dom.scm",
"line":163,
"documentation":""}
,
"dl":{
"filename":"dom/scheme-dom.scm",
"line":167,
"documentation":""}
,
"dt":{
"filename":"dom/scheme-dom.scm",
"line":170,
"documentation":""}
,
"em":{
"filename":"dom/scheme-dom.scm",
"line":173,
"documentation":""}
,
"embed":{
"filename":"dom/scheme-dom.scm",
"line":176,
"documentation":""}
,
"fieldset":{
"filename":"dom/scheme-dom.scm",
"line":179,
"documentation":""}
,
"figcaption":{
"filename":"dom/scheme-dom.scm",
"line":182,
"documentation":""}
,
"figure":{
"filename":"dom/scheme-dom.scm",
"line":185,
"documentation":""}
,
"footer":{
"filename":"dom/scheme-dom.scm",
"line":188,
"documentation":""}
,
"form":{
"filename":"dom/scheme-dom.scm",
"line":191,
"documentation":""}
,
"h1":{
"filename":"dom/scheme-dom.scm",
"line":194,
"documentation":""}
,
"h2":{
"filename":"dom/scheme-dom.scm",
"line":197,
"documentation":""}
,
"h3":{
"filename":"dom/scheme-dom.scm",
"line":200,
"documentation":""}
,
"h4":{
"filename":"dom/scheme-dom.scm",
"line":203,
"documentation":""}
,
"h5":{
"filename":"dom/scheme-dom.scm",
"line":206,
"documentation":""}
,
"h6":{
"filename":"dom/scheme-dom.scm",
"line":209,
"documentation":""}
,
"head":{
"filename":"dom/scheme-dom.scm",
"line":212,
"documentation":""}
,
"header":{
"filename":"dom/scheme-dom.scm",
"line":215,
"documentation":""}
,
"hgroup":{
"filename":"dom/scheme-dom.scm",
"line":218,
"documentation":""}
,
"hr":{
"filename":"dom/scheme-dom.scm",
"line":221,
"documentation":""}
,
"html":{
"filename":"dom/scheme-dom.scm",
"line":224,
"documentation":""}
,
"htmlmap":{
"filename":"dom/scheme-dom.scm",
"line":227,
"documentation":""}
,
"i":{
"filename":"dom/scheme-dom.scm",
"line":230,
"documentation":""}
,
"iframe":{
"filename":"dom/scheme-dom.scm",
"line":233,
"documentation":""}
,
"img":{
"filename":"dom/scheme-dom.scm",
"line":236,
"documentation":""}
,
"input":{
"filename":"dom/scheme-dom.scm",
"line":239,
"documentation":""}
,
"ins":{
"filename":"dom/scheme-dom.scm",
"line":242,
"documentation":""}
,
"kbd":{
"filename":"dom/scheme-dom.scm",
"line":245,
"documentation":""}
,
"keygen":{
"filename":"dom/scheme-dom.scm",
"line":248,
"documentation":""}
,
"label":{
"filename":"dom/scheme-dom.scm",
"line":251,
"documentation":""}
,
"legend":{
"filename":"dom/scheme-dom.scm",
"line":254,
"documentation":""}
,
"li":{
"filename":"dom/scheme-dom.scm",
"line":257,
"documentation":""}
,
"link":{
"filename":"dom/scheme-dom.scm",
"line":260,
"documentation":""}
,
"mark":{
"filename":"dom/scheme-dom.scm",
"line":264,
"documentation":""}
,
"menu":{
"filename":"dom/scheme-dom.scm",
"line":267,
"documentation":""}
,
"meta":{
"filename":"dom/scheme-dom.scm",
"line":270,
"documentation":""}
,
"meter":{
"filename":"dom/scheme-dom.scm",
"line":273,
"documentation":""}
,
"nav":{
"filename":"dom/scheme-dom.scm",
"line":276,
"documentation":""}
,
"noscript":{
"filename":"dom/scheme-dom.scm",
"line":280,
"documentation":""}
,
"object":{
"filename":"dom/scheme-dom.scm",
"line":283,
"documentation":""}
,
"ol":{
"filename":"dom/scheme-dom.scm",
"line":286,
"documentation":""}
,
"optgroup":{
"filename":"dom/scheme-dom.scm",
"line":289,
"documentation":""}
,
"option":{
"filename":"dom/scheme-dom.scm",
"line":292,
"documentation":""}
,
"output":{
"filename":"dom/scheme-dom.scm",
"line":295,
"documentation":""}
,
"p":{
"filename":"dom/scheme-dom.scm",
"line":298,
"documentation":""}
,
"param":{
"filename":"dom/scheme-dom.scm",
"line":301,
"documentation":""}
,
"pre":{
"filename":"dom/scheme-dom.scm",
"line":304,
"documentation":""}
,
"progress":{
"filename":"dom/scheme-dom.scm",
"line":307,
"documentation":""}
,
"q":{
"filename":"dom/scheme-dom.scm",
"line":310,
"documentation":""}
,
"rp":{
"filename":"dom/scheme-dom.scm",
"line":313,
"documentation":""}
,
"rt":{
"filename":"dom/scheme-dom.scm",
"line":316,
"documentation":""}
,
"ruby":{
"filename":"dom/scheme-dom.scm",
"line":319,
"documentation":""}
,
"samp":{
"filename":"dom/scheme-dom.scm",
"line":323,
"documentation":""}
,
"script":{
"filename":"dom/scheme-dom.scm",
"line":326,
"documentation":""}
,
"section":{
"filename":"dom/scheme-dom.scm",
"line":329,
"documentation":""}
,
"select":{
"filename":"dom/scheme-dom.scm",
"line":332,
"documentation":""}
,
"small":{
"filename":"dom/scheme-dom.scm",
"line":335,
"documentation":""}
,
"source":{
"filename":"dom/scheme-dom.scm",
"line":338,
"documentation":""}
,
"span":{
"filename":"dom/scheme-dom.scm",
"line":341,
"documentation":""}
,
"strong":{
"filename":"dom/scheme-dom.scm",
"line":344,
"documentation":""}
,
"style":{
"filename":"dom/scheme-dom.scm",
"line":347,
"documentation":""}
,
"sub":{
"filename":"dom/scheme-dom.scm",
"line":350,
"documentation":""}
,
"summary":{
"filename":"dom/scheme-dom.scm",
"line":353,
"documentation":""}
,
"sup":{
"filename":"dom/scheme-dom.scm",
"line":356,
"documentation":""}
,
"svg":{
"filename":"dom/scheme-dom.scm",
"line":359,
"documentation":""}
,
"table":{
"filename":"dom/scheme-dom.scm",
"line":362,
"documentation":""}
,
"tbody":{
"filename":"dom/scheme-dom.scm",
"line":365,
"documentation":""}
,
"td":{
"filename":"dom/scheme-dom.scm",
"line":368,
"documentation":""}
,
"textarea":{
"filename":"dom/scheme-dom.scm",
"line":371,
"documentation":""}
,
"tfoot":{
"filename":"dom/scheme-dom.scm",
"line":374,
"documentation":""}
,
"th":{
"filename":"dom/scheme-dom.scm",
"line":377,
"documentation":""}
,
"thead":{
"filename":"dom/scheme-dom.scm",
"line":380,
"documentation":""}
,
"time":{
"filename":"dom/scheme-dom.scm",
"line":383,
"documentation":""}
,
"title":{
"filename":"dom/scheme-dom.scm",
"line":386,
"documentation":""}
,
"tr":{
"filename":"dom/scheme-dom.scm",
"line":389,
"documentation":""}
,
"track":{
"filename":"dom/scheme-dom.scm",
"line":392,
"documentation":""}
,
"u":{
"filename":"dom/scheme-dom.scm",
"line":395,
"documentation":""}
,
"ul":{
"filename":"dom/scheme-dom.scm",
"line":398,
"documentation":""}
,
"var":{
"filename":"dom/scheme-dom.scm",
"line":401,
"documentation":""}
,
"video":{
"filename":"dom/scheme-dom.scm",
"line":404,
"documentation":""}
,
"wbr":{
"filename":"dom/scheme-dom.scm",
"line":407,
"documentation":""}
,
"internal-image":{
"filename":"dom/synthetic-dom.scm",
"line":5,
"documentation":""}
,
"ulist":{
"filename":"dom/synthetic-dom.scm",
"line":11,
"documentation":""}
,
"olist":{
"filename":"dom/synthetic-dom.scm",
"line":14,
"documentation":""}
,
"html-list":{
"filename":"dom/synthetic-dom.scm",
"line":18,
"documentation":""}
,
"html-list-rec":{
"filename":"dom/synthetic-dom.scm",
"line":21,
"documentation":""}
,
"codeblock":{
"filename":"dom/synthetic-dom.scm",
"line":26,
"documentation":""}
,
"classdiv":{
"filename":"dom/synthetic-dom.scm",
"line":29,
"documentation":""}
,
"generic-span":{
"filename":"dom/synthetic-dom.scm",
"line":34,
"documentation":""}
,
"box":{
"filename":"dom/synthetic-dom.scm",
"line":39,
"documentation":""}
,
"box-top":{
"filename":"dom/synthetic-dom.scm",
"line":42,
"documentation":""}
,
"color-box":{
"filename":"dom/synthetic-dom.scm",
"line":45,
"documentation":""}
,
"color-box-top":{
"filename":"dom/synthetic-dom.scm",
"line":49,
"documentation":""}
,
"double-box":{
"filename":"dom/synthetic-dom.scm",
"line":53,
"documentation":""}
,
"double-grey-box":{
"filename":"dom/synthetic-dom.scm",
"line":56,
"documentation":""}
,
"double-round-box":{
"filename":"dom/synthetic-dom.scm",
"line":59,
"documentation":""}
,
"double-round-grey-box":{
"filename":"dom/synthetic-dom.scm",
"line":62,
"documentation":""}
,
"grey-box":{
"filename":"dom/synthetic-dom.scm",
"line":65,
"documentation":""}
,
"hang":{
"filename":"dom/synthetic-dom.scm",
"line":68,
"documentation":""}
,
"mono-font":{
"filename":"dom/synthetic-dom.scm",
"line":71,
"documentation":""}
,
"poem":{
"filename":"dom/synthetic-dom.scm",
"line":74,
"documentation":""}
,
"round-list":{
"filename":"dom/synthetic-dom.scm",
"line":77,
"documentation":""}
,
"round-list-item":{
"filename":"dom/synthetic-dom.scm",
"line":80,
"documentation":""}
,
"sans-font":{
"filename":"dom/synthetic-dom.scm",
"line":83,
"documentation":""}
,
"serif-font":{
"filename":"dom/synthetic-dom.scm",
"line":86,
"documentation":""}
,
"smallcaps-font":{
"filename":"dom/synthetic-dom.scm",
"line":89,
"documentation":""}
,
"symbol-font":{
"filename":"dom/synthetic-dom.scm",
"line":92,
"documentation":""}
,
"round-box":{
"filename":"dom/synthetic-dom.scm",
"line":95,
"documentation":""}
,
"round-grey-box":{
"filename":"dom/synthetic-dom.scm",
"line":98,
"documentation":""}
,
"warning-box":{
"filename":"dom/synthetic-dom.scm",
"line":101,
"documentation":""}
,
"youtube":{
"filename":"dom/synthetic-dom.scm",
"line":104,
"documentation":""}
,
"css-string":{
"filename":"dom/scheme-css.scm",
"line":4,
"documentation":""}
,
"install-css":{
"filename":"dom/scheme-css.scm",
"line":9,
"documentation":""}
,
"proc-css-list":{
"filename":"dom/scheme-css.scm",
"line":20,
"documentation":""}
,
"proc-css":{
"filename":"dom/scheme-css.scm",
"line":24,
"documentation":""}
,
"proc-css-rules":{
"filename":"dom/scheme-css.scm",
"line":28,
"documentation":""}
,
"load-stylesheet":{
"filename":"dom/scheme-css.scm",
"line":33,
"documentation":""}
,
"grid-container":{
"filename":"dom/scheme-css.scm",
"line":37,
"documentation":""}
,
"gen_handler":{
"filename":"dom/wired.scm",
"line":4,
"documentation":""}
,
"select_handler":{
"filename":"dom/wired.scm",
"line":15,
"documentation":""}
,
"click_handler":{
"filename":"dom/wired.scm",
"line":24,
"documentation":""}
,
"change_handler":{
"filename":"dom/wired.scm",
"line":27,
"documentation":""}
,
"input_handler":{
"filename":"dom/wired.scm",
"line":30,
"documentation":""}
,
"wire-click":{
"filename":"dom/wired.scm",
"line":34,
"documentation":""}
,
"wire-buttons":{
"filename":"dom/wired.scm",
"line":39,
"documentation":""}
,
"wire-button":{
"filename":"dom/wired.scm",
"line":42,
"documentation":""}
,
"wire-text-inputs":{
"filename":"dom/wired.scm",
"line":45,
"documentation":""}
,
"wire-text-input":{
"filename":"dom/wired.scm",
"line":48,
"documentation":""}
,
"wire-change":{
"filename":"dom/wired.scm",
"line":52,
"documentation":""}
,
"wire-submit-inputs":{
"filename":"dom/wired.scm",
"line":56,
"documentation":""}
,
"wire-submit-input":{
"filename":"dom/wired.scm",
"line":59,
"documentation":""}
,
"wire-ui":{
"filename":"dom/wired.scm",
"line":62,
"documentation":""}
,
"randomize-select!":{
"filename":"dom/dom-utilities.scm",
"line":4,
"documentation":""}
,
"populate-select":{
"filename":"dom/dom-utilities.scm",
"line":9,
"documentation":""}
,
"generate-select-items-rec":{
"filename":"dom/dom-utilities.scm",
"line":13,
"documentation":""}
,
"checkbox-checked?":{
"filename":"dom/dom-utilities.scm",
"line":19,
"documentation":""}
,
"set-checkbox-checked!":{
"filename":"dom/dom-utilities.scm",
"line":22,
"documentation":""}
,
"fa-icon-gen":{
"filename":"font-awesome/font-awesome.scm",
"line":29,
"documentation":""}
,
"fa-icon":{
"filename":"font-awesome/font-awesome.scm",
"line":32,
"documentation":""}
,
"build-tree-view":{
"filename":"treeview/treeview.scm",
"line":1,
"documentation":""}
,
"get-tree-folder":{
"filename":"treeview/treeview.scm",
"line":24,
"documentation":""}
,
"treeview":{
"filename":"treeview/treeview.scm",
"line":29,
"documentation":""}
,
"treenode":{
"filename":"treeview/treeview.scm",
"line":35,
"documentation":""}
,
"treeleaf":{
"filename":"treeview/treeview.scm",
"line":45,
"documentation":""}
,
"set-cm-editor-text!":{
"filename":"codemirror/codemirror-extensions.js",
"line":5,
"documentation":""}
,
"cm-editor-show":{
"filename":"codemirror/codemirror-extensions.js",
"line":22,
"documentation":""}
,
"cm-editor-hide":{
"filename":"codemirror/codemirror-extensions.js",
"line":33,
"documentation":""}
,
"cm-editor-hide-all":{
"filename":"codemirror/codemirror-extensions.js",
"line":44,
"documentation":""}
,
"cm-editor-get-current-symbol":{
"filename":"codemirror/codemirror-extensions.js",
"line":52,
"documentation":""}
,
"cm-editor-retrieve-documentation":{
"filename":"codemirror/codemirror-extensions.js",
"line":133,
"documentation":""}
,
"cm-editor-retrieve-definition":{
"filename":"codemirror/codemirror-extensions.js",
"line":147,
"documentation":""}
,
"cm-editor-eval-js-selection!":{
"filename":"codemirror/codemirror-extensions.js",
"line":147,
"documentation":""}
,
"cm-editor-eval-selection-or-expr-before-cursor!":{
"filename":"codemirror/codemirror-extensions.js",
"line":176,
"documentation":""}
,
"cm-eval-editor-buffer!":{
"filename":"codemirror/codemirror-extensions.js",
"line":223,
"documentation":""}
,
"cm-editor-undo!":{
"filename":"codemirror/codemirror-extensions.js",
"line":247,
"documentation":""}
,
"cm-editor-redo!":{
"filename":"codemirror/codemirror-extensions.js",
"line":259,
"documentation":""}
,
"is-cm-editor-clean?":{
"filename":"codemirror/codemirror-extensions.js",
"line":271,
"documentation":""}
,
"set-cm-editor-clean!":{
"filename":"codemirror/codemirror-extensions.js",
"line":285,
"documentation":""}
,
"get-cm-editor-text":{
"filename":"codemirror/codemirror-extensions.js",
"line":298,
"documentation":""}
,
"focus-cm-editor-component!":{
"filename":"codemirror/codemirror-extensions.js",
"line":310,
"documentation":""}
,
"refresh-cm-editor-component!":{
"filename":"codemirror/codemirror-extensions.js",
"line":322,
"documentation":""}
,
"destroy-cm-editor!":{
"filename":"codemirror/codemirror-extensions.js",
"line":333,
"documentation":""}
,
"get-cm-editor-ids":{
"filename":"codemirror/codemirror-extensions.js",
"line":356,
"documentation":""}
,
"init-cm-editor!":{
"filename":"codemirror/codemirror-extensions.js",
"line":361,
"documentation":""}
,
"cm-editor-find":{
"filename":"codemirror/codemirror-extensions.js",
"line":684,
"documentation":""}
,
"cm-editor-replace-all":{
"filename":"codemirror/codemirror-extensions.js",
"line":687,
"documentation":""}
,
"cm-editor-replace":{
"filename":"codemirror/codemirror-extensions.js",
"line":690,
"documentation":""}
,
"cm-editor-refresh":{
"filename":"codemirror/codemirror-extensions.js",
"line":693,
"documentation":""}
,
"cm-editor-get-text":{
"filename":"codemirror/codemirror-extensions.js",
"line":698,
"documentation":""}
,
"cm-editor-set-text":{
"filename":"codemirror/codemirror-extensions.js",
"line":702,
"documentation":""}
,
"cm-editor-get-selected-text":{
"filename":"codemirror/codemirror-extensions.js",
"line":706,
"documentation":""}
,
"cm-editor-delete-selected-text":{
"filename":"codemirror/codemirror-extensions.js",
"line":709,
"documentation":""}
,
"cm-editor-set-bold":{
"filename":"codemirror/codemirror-extensions.js",
"line":712,
"documentation":""}
,
"cm-editor-set-italic":{
"filename":"codemirror/codemirror-extensions.js",
"line":715,
"documentation":""}
,
"cm-editor-set-superscript":{
"filename":"codemirror/codemirror-extensions.js",
"line":718,
"documentation":""}
,
"cm-editor-set-subscript":{
"filename":"codemirror/codemirror-extensions.js",
"line":721,
"documentation":""}
,
"cm-editor-set-strikeout":{
"filename":"codemirror/codemirror-extensions.js",
"line":724,
"documentation":""}
,
"cm-editor-set-bulleted-list":{
"filename":"codemirror/codemirror-extensions.js",
"line":727,
"documentation":""}
,
"cm-editor-set-numbered-list":{
"filename":"codemirror/codemirror-extensions.js",
"line":730,
"documentation":""}
,
"cm-editor-set-block-quote":{
"filename":"codemirror/codemirror-extensions.js",
"line":733,
"documentation":""}
,
"cm-editor-set-poetry":{
"filename":"codemirror/codemirror-extensions.js",
"line":736,
"documentation":""}
,
"cm-editor-set-code":{
"filename":"codemirror/codemirror-extensions.js",
"line":739,
"documentation":""}
,
"cm-editor-set-center":{
"filename":"codemirror/codemirror-extensions.js",
"line":742,
"documentation":""}
,
"cm-editor-set-justify":{
"filename":"codemirror/codemirror-extensions.js",
"line":745,
"documentation":""}
,
"cm-editor-set-align-left":{
"filename":"codemirror/codemirror-extensions.js",
"line":748,
"documentation":""}
,
"cm-editor-set-align-right":{
"filename":"codemirror/codemirror-extensions.js",
"line":751,
"documentation":""}
,
"cm-editor-set-comment":{
"filename":"codemirror/codemirror-extensions.js",
"line":754,
"documentation":""}
,
"cm-editor-set-note":{
"filename":"codemirror/codemirror-extensions.js",
"line":758,
"documentation":""}
,
"cm-editor-set-heading":{
"filename":"codemirror/codemirror-extensions.js",
"line":761,
"documentation":""}
,
"cm-editor-set-math":{
"filename":"codemirror/codemirror-extensions.js",
"line":765,
"documentation":""}
,
"patch-poetry":{
"filename":"codemirror/codemirror-extensions.js",
"line":769,
"documentation":""}
,
"code-editor-add-filename-to-dropdown":{
"filename":"code-editor/code-editor.scm",
"line":15,
"documentation":""}
,
"code-editor-remove-filename-from-dropdown":{
"filename":"code-editor/code-editor.scm",
"line":22,
"documentation":""}
,
"code-editor-add-filename-to-file-list":{
"filename":"code-editor/code-editor.scm",
"line":26,
"documentation":""}
,
"code-editor-remove-filename-from-file-list":{
"filename":"code-editor/code-editor.scm",
"line":31,
"documentation":""}
,
"code-editor-element-for-filename":{
"filename":"code-editor/code-editor.scm",
"line":34,
"documentation":""}
,
"code-editor-id-for-filename":{
"filename":"code-editor/code-editor.scm",
"line":37,
"documentation":""}
,
"code-editor-add-balename-to-bale-list":{
"filename":"code-editor/code-editor.scm",
"line":46,
"documentation":""}
,
"code-editor-remove-balename-from-bale-list":{
"filename":"code-editor/code-editor.scm",
"line":50,
"documentation":""}
,
"display-file-editor":{
"filename":"code-editor/code-editor.scm",
"line":54,
"documentation":""}
,
"is-text-file?":{
"filename":"code-editor/code-editor.scm",
"line":59,
"documentation":""}
,
"display-text-file-editor":{
"filename":"code-editor/code-editor.scm",
"line":76,
"documentation":""}
,
"show-editor-buttons":{
"filename":"code-editor/code-editor.scm",
"line":85,
"documentation":""}
,
"set-active-editor":{
"filename":"code-editor/code-editor.scm",
"line":90,
"documentation":""}
,
"create-text-file-editor":{
"filename":"code-editor/code-editor.scm",
"line":101,
"documentation":""}
,
"editor-dropdown-chosen":{
"filename":"code-editor/code-editor.scm",
"line":113,
"documentation":""}
,
"show-code-editor":{
"filename":"code-editor/code-editor.scm",
"line":116,
"documentation":""}
,
"hide-code-editor":{
"filename":"code-editor/code-editor.scm",
"line":125,
"documentation":""}
,
"fronkensteen-editor-delete-bale_click":{
"filename":"code-editor/code-editor.scm",
"line":128,
"documentation":""}
,
"fronkensteen-editor-delete-file_click":{
"filename":"code-editor/code-editor.scm",
"line":138,
"documentation":""}
,
"close-open-bale-files":{
"filename":"code-editor/code-editor.scm",
"line":151,
"documentation":""}
,
"close-if-open":{
"filename":"code-editor/code-editor.scm",
"line":158,
"documentation":""}
,
"fronkensteen-editor-hide-button_click":{
"filename":"code-editor/code-editor.scm",
"line":164,
"documentation":""}
,
"fronkensteen-editor-save-button_click":{
"filename":"code-editor/code-editor.scm",
"line":167,
"documentation":""}
,
"fronkensteen-editor-scheme-eval-button_click":{
"filename":"code-editor/code-editor.scm",
"line":172,
"documentation":""}
,
"fronkensteen-editor-javascript-eval-button_click":{
"filename":"code-editor/code-editor.scm",
"line":179,
"documentation":""}
,
"fronkensteen-editor-scheme-doc-button_click":{
"filename":"code-editor/code-editor.scm",
"line":186,
"documentation":""}
,
"fronkensteen-editor-scheme-definition-button_click":{
"filename":"code-editor/code-editor.scm",
"line":188,
"documentation":""}
,
"display-procedure-definition":{
"filename":"code-editor/code-editor.scm",
"line":198,
"documentation":""}
,
"fronkensteen-editor-scheme-run-button_click":{
"filename":"code-editor/code-editor.scm",
"line":203,
"documentation":""}
,
"save-editor-file":{
"filename":"code-editor/code-editor.scm",
"line":211,
"documentation":""}
,
"fronkensteen-close-editor-file":{
"filename":"code-editor/code-editor.scm",
"line":221,
"documentation":""}
,
"fronkensteen-editor-close-button_click":{
"filename":"code-editor/code-editor.scm",
"line":242,
"documentation":""}
,
"editor-mode-for-file-extension":{
"filename":"code-editor/code-editor.scm",
"line":251,
"documentation":""}
,
"check-abandon":{
"filename":"code-editor/code-editor.scm",
"line":264,
"documentation":""}
,
"check-editor-save":{
"filename":"code-editor/code-editor.scm",
"line":271,
"documentation":""}
,
"check-for-dirty-editors":{
"filename":"code-editor/code-editor.scm",
"line":282,
"documentation":""}
,
"process-dirty-editors":{
"filename":"code-editor/code-editor.scm",
"line":286,
"documentation":""}
,
"read-editor-text-file":{
"filename":"code-editor/code-editor.scm",
"line":293,
"documentation":""}
,
"write-editor-text-file":{
"filename":"code-editor/code-editor.scm",
"line":296,
"documentation":""}
,
"fronkensteen-editor-controls":{
"filename":"code-editor/code-editor-ui.scm",
"line":4,
"documentation":""}
,
"fronkensteen-editor-sidebar":{
"filename":"code-editor/code-editor-ui.scm",
"line":30,
"documentation":""}
,
"fronkensteen-editor-workspace":{
"filename":"code-editor/code-editor-ui.scm",
"line":46,
"documentation":""}
,
"tree-file-clicked":{
"filename":"code-editor/code-editor-file-tree.scm",
"line":1,
"documentation":""}
,
"markdown ":{
"filename":"markdown-it/markdown-it-extensions.js",
"line":12,
"documentation":""}
,
"scheme->json":{
"filename":"json/json.scm",
"line":2,
"documentation":""}
,
"generate-json-object":{
"filename":"json/json.scm",
"line":12,
"documentation":""}
,
"generate-json-object-rec":{
"filename":"json/json.scm",
"line":17,
"documentation":""}
,
"generate-json-string":{
"filename":"json/json.scm",
"line":27,
"documentation":""}
,
"generate-json-number":{
"filename":"json/json.scm",
"line":30,
"documentation":""}
,
"generate-json-key-value":{
"filename":"json/json.scm",
"line":33,
"documentation":""}
,
"generate-json-vector":{
"filename":"json/json.scm",
"line":40,
"documentation":""}
,
"generate-json-vector-items":{
"filename":"json/json.scm",
"line":46,
"documentation":""}
,
"json->scheme":{
"filename":"json/json-extensions.js",
"line":3,
"documentation":""}
,
"launch-remote-repl-server":{
"filename":"remote-repl/remote-repl.js",
"line":90,
"documentation":""}
,
"remote-evaluate":{
"filename":"remote-repl/remote-repl.js",
"line":94,
"documentation":""}
,
"launch-remote-repl-client":{
"filename":"remote-repl/remote-repl.js",
"line":107,
"documentation":""}
,
"beautify-html ":{
"filename":"beautify-html/beautify-html-extensions.js",
"line":4,
"documentation":""}
,
"remove-comments":{
"filename":"text-processor/text-processor-extensions.js",
"line":5,
"documentation":""}
,
"process-poetry":{
"filename":"text-processor/text-processor-extensions.js",
"line":14,
"documentation":""}
,
"process-alignment":{
"filename":"text-processor/text-processor-extensions.js",
"line":25,
"documentation":""}
,
"process-notes":{
"filename":"text-processor/text-processor-extensions.js",
"line":40,
"documentation":""}
,
"embedded-scheme-enabled?":{
"filename":"text-processor/text-processor-extensions.js",
"line":60,
"documentation":""}
,
"enable-embedded-scheme":{
"filename":"text-processor/text-processor-extensions.js",
"line":64,
"documentation":""}
,
"disable-embedded-scheme":{
"filename":"text-processor/text-processor-extensions.js",
"line":69,
"documentation":""}
,
"process-embedded-scheme":{
"filename":"text-processor/text-processor-extensions.js",
"line":73,
"documentation":""}
,
"process-hashtags":{
"filename":"text-processor/text-processor-extensions.js",
"line":93,
"documentation":""}
,
"process-wikilinks":{
"filename":"text-processor/text-processor-extensions.js",
"line":103,
"documentation":""}
,
"externalize-hyperlinks ":{
"filename":"text-processor/text-processor-extensions.js",
"line":117,
"documentation":""}
,
"text-processor-chain":{
"filename":"text-processor/text-processor.scm",
"line":0,
"documentation":""}
,
"process-latex":{
"filename":"mathjax-latex/mathjax-latex-extensions.js",
"line":4,
"documentation":""}
,
"%macroexpand":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"%macroexpand-1":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"..":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"<<":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"active-panel":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"add-ui-panel":{
"filename":"root-ui/root-ui.scm",
"line":4,
"documentation":""}
,
"and":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"baseload":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"beautify-html":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"begin":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"block-db":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"call-with-current-continuation":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"case":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"case-lambda":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"cm-editor-get-procedure-at-cursor":{
"filename":"codemirror/codemirror-extensions.js",
"line":135,
"documentation":""}
,
"collection-db":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"command-line":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"cond":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"console-debug":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"console-error":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"console-info":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"console-log":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"console-warn":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"current-bale":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"dec!":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"define":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"define-enumeration":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"define-macro":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"define-record-type":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"delay":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"delay-force":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"delete-file":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"do":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"documentation-display":{
"filename":"documentation/documentation-ui.scm",
"line":32,
"documentation":""}
,
"documentation-search":{
"filename":"documentation/documentation-ui.scm",
"line":40,
"documentation":""}
,
"dotimes":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"editor-hash":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"element-clear!":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"elems":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"exit":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"externalize-hyperlinks":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"file-exists?":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"fronkensteen-active-editor-file":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"fronkensteen-documentation-done-button_click":{
"filename":"documentation/documentation.scm",
"line":20,
"documentation":""}
,
"fronkensteen-export-documentation-button_click":{
"filename":"documentation/documentation.scm",
"line":32,
"documentation":""}
,
"fronkensteen-is-local-editor":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"fronkensteen-rebuild-documentation-button_click":{
"filename":"documentation/documentation.scm",
"line":29,
"documentation":""}
,
"fronkensteen-selected-file":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"fronkensteen-update-documentation-button_click":{
"filename":"documentation/documentation.scm",
"line":23,
"documentation":""}
,
"gen-css-id":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"gen-element-id":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"gen-html-id":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"gen-js-id":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"get-environment-variable":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"get-environment-variables":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"hide-ui-panel":{
"filename":"root-ui/root-ui.scm",
"line":13,
"documentation":""}
,
"html-4.01-frameset":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"html-4.01-strict":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"html-4.01-transitional":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"html5":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"if":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"inc!":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"init-code-editor":{
"filename":"code-editor/code-editor-ui.scm",
"line":50,
"documentation":""}
,
"init-documentation":{
"filename":"documentation/documentation-ui.scm",
"line":47,
"documentation":""}
,
"install-stylesheet":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"lambda":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"let":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"let*":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"let*-values":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"let-values":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"let1":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"letrec":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"letrec*":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"markdown":{
"filename":"markdown-it/markdown-it-extensions.js",
"line":12,
"documentation":""}
,
"mime-type":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"mla-level-counter":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"no-dash-uuid":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"or":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"panel-stack":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"place-caret-at-end":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"place-caret-at-start":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"pop-ui-panel":{
"filename":"root-ui/root-ui.scm",
"line":20,
"documentation":""}
,
"push-ui-panel":{
"filename":"root-ui/root-ui.scm",
"line":16,
"documentation":""}
,
"quasiquote":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"quote":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"receive":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"record-constructor-descriptor":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"record-type-descriptor":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"render-procedure-definition-text":{
"filename":"documentation/documentation-extensions.js",
"line":104,
"documentation":""}
,
"roman-numeral-bands":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"roman-numeral-strings-lower":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"roman-numeral-strings-upper":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"scroll-element-into-view":{
"filename":"dom/dom-extensions.js",
"line":237,
"documentation":""}
,
"set!":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"set-content-editable-change-handler!":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"set-content-editable-save-handler!":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"show-procedure-documentation":{
"filename":"documentation/documentation.scm",
"line":0,
"documentation":""}
,
"show-ui-panel":{
"filename":"root-ui/root-ui.scm",
"line":8,
"documentation":""}
,
"sort-order":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"sortable":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"unless":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"unquote":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"unquote-splicing":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"update-procedure-documentation!":{
"filename":"documentation/documentation-extensions.js",
"line":128,
"documentation":""}
,
"uuid":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"when":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"xhtml-1.0-frameset":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"xhtml-1.0-strict":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"xhtml-1.0-transitional":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"xhtml-1.1-dtd":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
,
"xhtml-basic-1.0":{
"filename":"(unspecified)",
"line":0,
"documentation":""}
}
