
(define (.page-history-button_click ev)
  (let ((target (js-ref ev "currentTarget")))
    (let ((id (<< "#" (element-read-attribute target "id"))))
      (set-popover (<<  id)
        (popup-list
          (build-page-history-display fronkensteen-page-history-list)) "bottom" (scheme->json '(("dismissable" . #t))))
     (toggle-popover id)
      (wire-ui)
      (% ".fronkensteen-history-entry" "on" "click" (lambda (ev)
        (destroy-popover id)
        (let ((target (js-ref ev "currentTarget")))
          (let ((title  (element-read-attribute target "title"))
                (type (element-read-attribute target "type"))
                (page-id (element-read-attribute target "page-id")))
                (remove-page-history id fronkensteen-page-history-list)
                (remove-page-history id fronkensteen-forward-page-history-list)
                (add-page-history title type page-id)
                (display-history-tos)
          )))))))
